import { describe, expect, it } from 'vitest';
import { MISSIONS } from '../src/renderer/missions';
import {
  LEFT_ENTRANCE_X,
  RIGHT_ENTRANCE_X,
  STORE_FRONT_Z,
} from '../src/renderer/missions/supermarketSites';
import { supermarket } from '../src/renderer/plugins/environments/supermarket';
import { SUPERMARKET_PLAN as SM } from '../src/renderer/scene/environment/SupermarketPlan';
import {
  decodePlanGrid,
  planEdges,
  supermarketIndoorAt,
  supermarketPixels,
} from '../src/renderer/hud/planLayers';

// The Supermarket's mission-map plan (`SupermarketPlan.ts`, generated by
// `scripts/generate-supermarket-plan.mjs`), held to the map it is a plan of.
//
// The two things that would make it lie to a pilot: a door drawn shut — the
// first cut went through the door heads and sealed the store — and a mark the
// map puts on something solid, or on no ground at all.

const outside = decodePlanGrid(SM.outside.data, SM.outside.w * SM.outside.h);
const floor = decodePlanGrid(SM.floor.data, SM.floor.w * SM.floor.h);

const cellOf = (g: typeof SM.outside | typeof SM.floor, x: number, z: number) => {
  const i = Math.floor((x - g.x0) / g.cell);
  const j = Math.floor((z - g.z0) / g.cell);
  return i < 0 || j < 0 || i >= g.w || j >= g.h ? -1 : j * g.w + i;
};
const outsideAt = (x: number, z: number) => outside[cellOf(SM.outside, x, z)];
const floorAt = (x: number, z: number) => {
  const k = cellOf(SM.floor, x, z);
  return k < 0 ? 0 : floor[k];
};
const KIND = { void: 0, asphalt: 1, paving: 2, grass: 3, paint: 4 };
const heightAt = (x: number, z: number) => (outsideAt(x, z) - SM.outside.struct) / 10;

describe('Supermarket plan: the outside', () => {
  it('covers the whole play area', () => {
    const { min, max } = supermarket.bounds;
    expect(SM.outside.x0).toBeLessThanOrEqual(min[0]);
    expect(SM.outside.z0).toBeLessThanOrEqual(min[2]);
    expect(SM.outside.x0 + SM.outside.w * SM.outside.cell).toBeGreaterThanOrEqual(max[0]);
    expect(SM.outside.z0 + SM.outside.h * SM.outside.cell).toBeGreaterThanOrEqual(max[2]);
  });

  it('reads the ground the pilot sees', () => {
    // The spawn pad, on the car park.
    expect(outsideAt(supermarket.spawn.position[0], supermarket.spawn.position[2])).toBe(
      KIND.asphalt,
    );
    // The grass bank round the edge, 2.4 m up and still ground, not a wall.
    expect(outsideAt(-85, 20)).toBe(KIND.grass);
    expect(outsideAt(0, 52)).toBe(KIND.grass);
    // The paved yard west of the store.
    expect(outsideAt(-72, -6)).toBe(KIND.paving);
    // Behind the store, where the model has no ground at all.
    expect(outsideAt(-72, -30)).toBe(KIND.void);
  });

  it('stands the roofs and the trucks up at their heights', () => {
    expect(heightAt(-40, -25)).toBeCloseTo(6, 0); // the store roof
    expect(heightAt(15, -25)).toBeCloseTo(6, 0); // the warehouse roof
    expect(heightAt(-9, 12)).toBeCloseTo(4.5, 0); // Truck 1's trailer
    expect(SM.outside.tallest).toBeGreaterThan(8); // the shopfront sign
  });

  it('draws an edge round the roofs, and every edge on the grid', () => {
    const edges = planEdges(
      outside,
      SM.outside,
      (v) => (v >= SM.outside.struct ? (v - SM.outside.struct) / 10 : 0),
      0.75,
      0,
    );
    expect(edges.length).toBeGreaterThan(0);
    for (let i = 0; i < edges.length; i += 4) {
      // Axis-aligned runs along cell boundaries.
      expect(edges[i] === edges[i + 2] || edges[i + 1] === edges[i + 3]).toBe(true);
    }
    // One of them is the store's front roof line, somewhere around z -3.
    let front = false;
    for (let i = 0; i < edges.length; i += 4) {
      if (edges[i + 1] === edges[i + 3] && Math.abs(edges[i + 1] + 3) < 1) {
        if (edges[i + 2] - edges[i] > 5) front = true;
      }
    }
    expect(front).toBe(true);
  });
});

describe('Supermarket plan: the floor plan', () => {
  it('is indoors under the store roof, and nowhere else', () => {
    expect(supermarketIndoorAt(-41.5, 1.5, -13.75)).toBe(true);
    expect(supermarketIndoorAt(-25, 1.5, -25)).toBe(true);
    // Over the roof is outside.
    expect(supermarketIndoorAt(-41.5, 7, -13.75)).toBe(false);
    // The car park.
    expect(
      supermarketIndoorAt(supermarket.spawn.position[0], 1.5, supermarket.spawn.position[2]),
    ).toBe(false);
    // The warehouse is sealed: no plan of somewhere the drone cannot go, it
    // stays a roof.
    expect(supermarketIndoorAt(15, 1.5, -25)).toBe(false);
  });

  it('draws both entrances open, and the wall either side of them', () => {
    for (const [x0, x1] of [LEFT_ENTRANCE_X, RIGHT_ENTRANCE_X]) {
      const mid = (x0 + x1) / 2;
      // Straight through the gap, from the wall line to a metre and a half in:
      // open floor all the way, so the doorway is drawn as a gap and not left
      // to the outside plan, where the portal over it would close it.
      for (let z = STORE_FRONT_Z - 0.05; z >= STORE_FRONT_Z - 1.5; z -= 0.125) {
        expect(floorAt(mid, z), `door at x ${mid}, z ${z}`).toBe(1);
      }
      // The map changes over in the doorway, not before it or two metres after.
      expect(supermarketIndoorAt(mid, 1.5, STORE_FRONT_Z - 0.3)).toBe(true);
      expect(supermarketIndoorAt(mid, 1.5, STORE_FRONT_Z + 0.5)).toBe(false);
      // At least a metre of it is drawn open, of the 1.5 m there is.
      let open = 0;
      for (let x = x0 - 1; x <= x1 + 1; x += SM.floor.cell) {
        if (floorAt(x + SM.floor.cell / 2, STORE_FRONT_Z - 0.05) === 1) open += SM.floor.cell;
      }
      expect(open).toBeGreaterThanOrEqual(1);
      expect(open).toBeLessThanOrEqual(1.75);
      // And the front either side of it is solid.
      expect(floorAt(x0 - 0.75, STORE_FRONT_Z - 0.05)).toBeGreaterThan(1);
      expect(floorAt(x1 + 0.75, STORE_FRONT_Z - 0.05)).toBeGreaterThan(1);
    }
  });

  it('has the store floor open, and the shelving solid', () => {
    let open = 0;
    let solid = 0;
    for (const v of floor) {
      if (v === 1) open++;
      else if (v >= 2) solid++;
    }
    // Most of the store is floor a drone can reach from the car park.
    expect(open).toBeGreaterThan(solid);
    // An aisle's shelving, 3.1 m tall: a run of solid cells at shelf height.
    let shelf = 0;
    for (const v of floor) if (v >= 2 && (v - 2) / 10 >= 2.8 && (v - 2) / 10 <= 3.5) shelf++;
    expect(shelf).toBeGreaterThan(500);
  });

  it('paints every cell the plan has, and nothing else', () => {
    const px = supermarketPixels();
    // Counted, not asserted per cell: a hundred thousand expects is seconds.
    let wrong = 0;
    for (let k = 0; k < outside.length; k++) {
      if (px.outside[k * 4 + 3] !== (outside[k] === 0 ? 0 : 255)) wrong++;
    }
    for (let k = 0; k < floor.length; k++) {
      if (px.floor[k * 4 + 3] !== (floor[k] === 0 ? 0 : 255)) wrong++;
    }
    expect(wrong).toBe(0);
  });
});

describe('Supermarket plan: every mission mark is on it', () => {
  const missions = MISSIONS.filter((m) => m.envId === supermarket.id);

  it('has missions to check', () => {
    expect(missions.length).toBeGreaterThan(0);
  });

  for (const m of missions) {
    it(`${m.name}: indoors on open floor, outdoors on ground`, () => {
      const zones = [
        ...Object.values(m.zones),
        ...(m.deliveries?.map((d) => d.zone) ?? []),
        ...(m.inspection?.points.map((p) => p.zone) ?? []),
      ];
      for (const z of zones) {
        const [x, zz] = z.at;
        if (supermarketIndoorAt(x, 1, zz)) {
          expect(floorAt(x, zz), `${z.label} at (${x}, ${zz})`).toBe(1);
        } else {
          expect(outsideAt(x, zz), `${z.label} at (${x}, ${zz})`).not.toBe(KIND.void);
        }
      }
    });
  }
});
