import type { Mission, MissionDelivery, MissionZone } from './types';

// ----------------------------------------------------------------------------
// Multi-Point Delivery — New York City.
//
// Three medical packages, one at a time, out of a central logistics hub. Collect
// A, place it, come back for B, place it, come back for C, place it, come home
// and land. Four points: one per delivery and one for the landing.
//
// THE JOB IS THE LOOP, WHICH IS WHY THERE ARE NO RINGS.
//
// Precision Delivery gates its release on fourteen checkpoints because its
// single crossing needs a route to be. This mission's difficulty is the workflow
// itself — three round trips, a payload that can only ever be the next one in
// order, and two destinations that are on ROOFS rather than on the street. A
// corridor of pink balls laid over that would be a second thing to follow at the
// moment the pilot is already counting packages.
//
// So `route` is empty, `requiredCheckpoints` is empty, the release gate is
// always open, and what stops a pilot skipping to package C is the state machine
// (`missionStore.runIndex`) rather than a line of scenery.
//
// EVERY COORDINATE HERE WAS MEASURED, NOT CHOSEN.
//
//     node scripts/check-multi-delivery-route.mjs
//
// reports the deck height under each mark, the clear air above it, and the
// corridor flown between them. Re-run it after ANY change to a number in this
// file or after regenerating the colliders.
//
// WHY ONLY TWO OF THE THREE DESTINATIONS ARE ROOFTOPS.
//
// The brief asks for three. Two things stand in the way, and both were measured
// rather than assumed.
//
// First the AIRCRAFT. Every mission is flown on the Guru, whose `maxAltitude` is
// 30 m, enforced as a soft ceiling in the flight controller. This city's roofs
// start at 45 m and the tallest is 112 m. Only a handful of structures come in
// under the ceiling at all, and they are all in the same north-west corner.
//
// Then the COLLIDERS. They are generated by merging same-band cells into
// rectangles and filling each one to the tallest thing inside it, so a roof with
// a parapet is solid up to the PARAPET: the drone stops one to two and a half
// metres above the slab the pilot can see, and a mark drawn where the drone
// stops hangs in the air over the roof. That is not worked around — it is built
// on. A destination declares the deck it rests on AND the roof underneath, and
// `MissionMarkers` draws a delivery platform between the two, which makes the
// collider honest: it was always claiming something solid was there.
//
// `scripts/check-roof-marks.mjs` reads the GLB itself and reports both numbers.
// Its sweep finds exactly TWO places in the city where a platform's whole
// footprint has real roof under it and a level deck above it — this mission's B
// and C. A is a street-level bay, because there is no third.
// ----------------------------------------------------------------------------

/**
 * The logistics hub: where all three packages wait, and where the drone lands at
 * the end.
 *
 * ONE PLACE, TWO ZONES. The pickup and the base sit on the same mark because on
 * this mission they are the same thing — the brief's "return to the logistics
 * centre" is the same flight as its "return to base", and giving them separate
 * marks would put two rings on one pad and ask the pilot which of them was
 * theirs. They are never live at the same time, so only one is ever drawn.
 *
 * IT IS DELIBERATELY NOT WHERE THE DRONE TAKES OFF FROM.
 *
 * It sat three metres from NYC's spawn to begin with, which is Precision
 * Delivery's pad. On a mission that carries ONE package that is fine — the pad
 * is bare and the box is somewhere else. Here it meant the pilot armed the
 * aircraft standing in the middle of three parcels, on top of the mark, with the
 * radar's P sitting under their own aircraft: the mission opened with its first
 * objective already met and nothing to fly to. Twenty-five metres down the cross
 * street the depot is a PLACE the pilot goes to, the first thing they do is
 * reposition, and the spawn is clear ground again.
 *
 * Measured, not moved by eye: 8.8 m of clear column here against 4.1 m at the
 * old pad, so it is also the better thing to descend onto — which matters, since
 * this one is landed on as well as collected from.
 */
const HUB: readonly [number, number] = [-25, 29];

/**
 * The cruise height the corridor between the marks is measured at, in metres.
 *
 * Above the street furniture — lamps, signs and traffic lights top out at
 * 10.5 m — and below the two roofs the mission delivers to, so the run out to
 * either of them is a climb rather than a level line. It is not a rail: nothing
 * is drawn at this height and nothing is scored on it. It is the number
 * `check-multi-delivery-route` samples the city at, and the number the docs
 * quote.
 */
const CRUISE = 20;

/**
 * One destination.
 *
 * The strict numbers are Precision Delivery's, deliberately: centred within
 * 1.8 m, low over its own deck, and actually stopped for a second. A pilot who
 * has flown mission 1 already knows what this test feels like, and the new thing
 * to learn here is that there are three of them and that two are on a roof.
 */
function bay(
  label: string,
  x: number,
  z: number,
  over: { deck: number; radius: number; max: number; standsOn?: number },
): MissionZone {
  return {
    kind: 'drop',
    at: [x, z],
    label,
    radius: over.radius,
    // Measured from THIS mark's own deck. On a roof that deck is twenty-five
    // metres up, and a band judged against the street would ask the pilot to
    // hover inside the building.
    band: { min: 0.3, max: over.max },
    maxGroundSpeed: 0.9,
    maxVerticalSpeed: 0.8,
    hold: 1,
    /*
     * THE WHOLE RING HAS TO STAND ON THE DECK.
     *
     * Both rooftop marks were placed by searching for the most clear air above
     * the slab, which put them a metre from the roof's west edge — the corner
     * furthest from the tower behind. A 1.8 m ring a metre from an edge has most
     * of itself hanging over the street, twenty-five metres up, and that is
     * exactly what it looked like: a target floating in the air beside the
     * building rather than a mark painted on its roof.
     *
     * They are now centred with the ring plus 0.6 m of margin entirely on the
     * declared deck, checked by `check-multi-delivery-route`, which samples the
     * ring's own perimeter. Clear air is what is traded for it — C drops from
     * 4.6 m to 3.9 — and that is the right way round: a mark you cannot read is
     * worse than a mark that is tight to fly to.
     */
    /*
     * THE DECK, ALWAYS DECLARED, even when it is nearly the street.
     *
     * `groundY` was only set on the roofs to begin with, on the reasoning that a
     * street mark is at the mission's own ground height. Bay A is not: it stands
     * on a sidewalk plate whose top is 0.12 m, and 0.12 m is exactly half of the
     * package. So the first box delivered there was placed at y = 0 and buried
     * to its waist in the pavement — and the height band the release is judged
     * on was 12 cm low too, over a kerb the drone would have set down on.
     *
     * The rule this leaves behind: a mark declares the surface it is ON, read
     * off the colliders, never the map's nominal ground. `check-multi-delivery-
     * route` measures it against every collider section INCLUDING the sidewalk
     * plates, which is what it failed to do the first time.
     */
    groundY: over.deck,
    // Set only on the rooftop, where the deck the aircraft rests on is the
    // collider's parapet-height top and the roof the pilot sees is a metre
    // below it. `MissionMarkers` builds a delivery platform across the gap —
    // see `MissionZone.padBase`.
    padBase: over.standsOn,
    // A ROOF is a slab with a lip, not a road: 3 cm of lift z-fights the deck
    // the ring is painted on from a low approach, which is exactly the approach
    // a rooftop delivery is flown on. A kerb 12 cm up is still flat ground and
    // wants the default.
    ringLift: over.deck > 1 ? 0.09 : undefined,
  };
}

/**
 * The three packages, in the order they are flown.
 *
 * The ORDER IS THE MISSION. `missionStore.runIndex` walks this list and is only
 * ever advanced by completing the delivery it is on, so B cannot be collected
 * before A is down and B cannot be placed on C's roof — while the index says B,
 * C's mark is not being tested by anything.
 *
 * A — SHORT, AND ON THE STREET. A loading bay 28 m south-west of the hub, in
 * open ground. It exists to teach the loop — collect, place, come back — and
 * nothing about it is meant to be hard.
 *
 * B — THE FIRST ROOF. 25.1 m up and 46 m out, on a delivery platform a metre
 * tall, with nine metres of clear air over it. The new skill is holding a hover
 * over a deck that is not the ground, and it should be learnt somewhere
 * forgiving.
 *
 * C — THE HARD ONE, AND THE FURTHEST. 26.5 m up and 59 m out, on a platform two
 * and a half metres tall, with 3.9 m of clear air beside it and the smallest
 * ring on the mission at 1.1 m. Its deck is high enough that the flight
 * controller's soft ceiling — 30 m, fading from 28 — has already begun taking
 * the climb rate off.
 *
 * The ramp runs on every axis at once: 28 m, 46 m, 59 m of range; street, then
 * an open roof, then a tight one; and 1.8 m, 1.8 m, 1.1 m of mark.
 */
const DELIVERIES: readonly MissionDelivery[] = [
  {
    id: 'a',
    name: 'Package A',
    cargo: 'Emergency medicine',
    // Measured: this corner is a sidewalk plate, not the road. See `bay`.
    zone: bay('Bay A', -45, 9, { deck: 0.12, radius: 1.8, max: 2 }),
  },
  {
    id: 'b',
    name: 'Package B',
    cargo: 'Medical equipment',
    // The one rooftop on the map a drone can be delivered to. `deck` is what
    // the aircraft rests on (the collider) and `standsOn` is the roof the pilot
    // sees; the platform drawn between them is what makes those the same place.
    zone: bay('Rooftop B', -13.5, 73, { deck: 25.14, radius: 1.8, max: 1.8, standsOn: 24.12 }),
    // West to the avenue at x = -29, north up it, then in over the roof. The
    // straight line from the hub goes through a block at z = 43.
    via: [
      [-29, 40],
      [-29, 70],
    ],
  },
  {
    id: 'c',
    name: 'Package C',
    cargo: 'Emergency supplies',
    // The second roof, and the harder one: a metre and a half taller than B, the
    // smallest ring on the mission, and the tightest air on the map. Its
    // platform is 2.4 m tall because that is how far the collider's deck stands
    // above the slab here.
    zone: bay('Rooftop C', 7, 78.5, { deck: 26.54, radius: 1.1, max: 1.4, standsOn: 24.15 }),
    // The same avenue as B, carried further north and round the top of the city.
    // Cutting east at B's own latitude would fly through B's building, which is
    // the one thing on this map tall enough to be in the way at cruise height.
    via: [
      [-29, 40],
      [-29, 84],
      [0, 86],
    ],
  },
];

/**
 * The way home from the last roof, as bare waypoints.
 *
 * NOT checkpoints — they score nothing and draw nothing. The straight line from
 * C back to the hub crosses a block, so a corridor check measured on it would be
 * measuring a flight nobody can make. This is C's own outbound line flown
 * backwards — over the top of the city, down the west avenue, in to the pad —
 * and it is what `check-multi-delivery-route` samples.
 */
const HOME_VIA: readonly (readonly [number, number])[] = [
  [0, 86],
  [-29, 84],
  [-29, 40],
];

/** Points, named once so the card, the medals and the star rungs cannot drift:
 *  one for each package placed, one for getting the aircraft home. */
const GOLD = 4;
const SILVER = 4;

export const multiPointDelivery: Mission = {
  id: 'multi-point-delivery',
  order: 3,
  name: 'Multi-Point Delivery',
  subtitle: 'Three packages, three destinations, one drone',
  kind: 'delivery',
  envId: 'new-york',
  blurb:
    'Run three medical packages out of a central hub to three destinations across the city, one at a time, and bring the drone home.',
  story:
    'A hospital network has gone to emergency distribution and the logistics hub has three packages on the pad. There is one drone on the roster and no second one behind it. Take them out one at a time — the hub will not release the next until the last one is down.',
  flow: [
    { label: 'Collect', note: 'One package at a time', art: 'collect' },
    { label: 'Deliver', note: 'A street bay, then two roofs', art: 'deliver' },
    { label: 'Return', note: 'Back to the hub for the next', art: 'city' },
    { label: 'Come home', note: 'Land on the hub pad', art: 'land' },
  ],
  objectives: [
    'Collect Package A from the logistics hub and place it in Bay A.',
    'Return to the hub for Package B and hold it over the Rooftop B platform.',
    'Return once more for Package C and hold it over the Rooftop C platform.',
    'Fly back to the hub and land on the pad.',
  ],
  mapNote: 'Buildings, roads and two reachable roofs',
  // Three round trips is roughly 270 m of flying plus six precision holds and a
  // landing, two of them onto rooftop platforms. Eleven minutes is a comfortable
  // flight and seven is a brisk one, which is the gap the top rating lives in.
  timeLimitSec: 660,
  parTimeSec: 420,
  groundY: 0,
  medals: { bronze: 3, silver: SILVER, gold: GOLD },
  routeAltitude: CRUISE,
  // No rings. See the header — the workflow is the difficulty here.
  route: [],
  /*
   * FULL THROTTLE AUTHORITY, while the sticks stay soft.
   *
   * This mission descends onto a mark six times — three collections and three
   * placements — where Precision Delivery does it twice. At the mission's own
   * command scale the keyboard's throttle axis moves at just over half rate,
   * which does not make the descent gentler (nothing here caps the rate) but
   * does make it take twice as long to command. Six times over that reads as an
   * aircraft that will not come down.
   *
   * One was not enough. At the aircraft's own rate the stick still takes most of
   * a second to reach the bottom, and six descents later that is most of a minute
   * spent waiting for the throttle to catch up with the decision. Above 1 it is
   * not a faster drone — the number is how quickly the AXIS travels, and the
   * descent is still the aircraft's — it is a pilot who can ask sooner.
   *
   * Roll, pitch and yaw keep the softening: placing the aircraft over a 1.1 m
   * ring on a roof is exactly what it is for.
   */
  throttleScale: 1.6,
  homeVia: HOME_VIA,
  deliveries: DELIVERIES,

  zones: {
    pickup: {
      kind: 'pickup',
      at: [HUB[0], HUB[1]],
      label: 'Logistics hub',
      /*
       * LOOSER THAN PRECISION DELIVERY'S PICKUP, on purpose.
       *
       * That one is 0.6 m across with a band reaching 0.9 m, and it is right for
       * a mission where the pilot collects ONCE: it makes the collection a
       * deliberate little piece of flying rather than something that happens as
       * they drift past overhead.
       *
       * This mission collects THREE TIMES. The same test flown three times is
       * not three times the lesson, it is the same lesson twice more with the
       * drone scraping the tarmac each go — and the second and third collections
       * come after a delivery, which is the part that is actually meant to be
       * hard. So the band reaches 2 m: the pilot still has to come down out of
       * the cruise and stop over the pad, but they are hovering at chest height
       * over the box rather than sitting on it.
       *
       * What is NOT relaxed is the rest of it. Still centred, still slowed, still
       * held for most of a second — a fly-past at 2 m does not collect anything,
       * which is the thing the tight version was really protecting.
       */
      radius: 1,
      band: { min: 0, max: 2 },
      maxGroundSpeed: 1.1,
      maxVerticalSpeed: 1,
      hold: 0.8,
    },
    // The first delivery's mark, as the single-drop half of the model still
    // sees it. The SAME object as `DELIVERIES[0].zone`, not a copy: anything
    // that reads `zones.drop` without asking which run is live gets the opening
    // destination rather than a stale duplicate that could drift from it.
    drop: DELIVERIES[0].zone,
    base: {
      kind: 'base',
      at: [HUB[0], HUB[1]],
      label: 'Logistics hub',
      radius: 2.5,
      band: { min: 0, max: 3 },
      // Landing is judged on ground contact and stillness in the Director; these
      // only gate the "LANDING ZONE REACHED" call.
      maxGroundSpeed: 12,
      maxVerticalSpeed: 12,
      hold: 0,
    },
  },

  // The city is 248 m by 196 m and this mission uses about a quarter of it, so
  // a pilot who has lost the hub can be a long way from anything that matters
  // with nothing on screen saying so. Wide enough to contain every mark with
  // room to overshoot, tight enough to be a real boundary.
  strayRadius: 95,

  // Mission Control. The generic keys are the fall-back; a key suffixed with a
  // package's id is preferred over it for that run — see `say()` in the
  // Director. That is what lets one crossing be narrated three times without
  // three copies of the same four lines.
  radio: {
    start: {
      id: 'start',
      text: 'The logistics hub is a short hop west of you, with three packages on the pad. Get over Package A, come down onto the box and hold steady.',
    },
    pickup: { id: 'pickup', text: 'Package on board. Your destination is marked.' },
    'pickup-a': {
      id: 'pickup-a',
      text: 'Package A attached. Bay A is south-west of you, down at street level.',
    },
    'pickup-b': {
      id: 'pickup-b',
      text: 'Package B attached. Rooftop B is north — climb to twenty-five metres and hold it over the platform. Do not put the skids down on a roof.',
    },
    'pickup-c': {
      id: 'pickup-c',
      text: 'Package C attached. Rooftop C is the furthest and the tightest of the three. Take your time.',
    },
    near: { id: 'near', text: 'Destination ahead. Start slowing down.' },
    'near-b': { id: 'near-b', text: 'Rooftop B ahead. Get your height on before you get there.' },
    'near-c': {
      id: 'near-c',
      text: 'Rooftop C ahead. It is higher than the last one and the mark is smaller.',
    },
    approach: { id: 'approach', text: 'Centre over the mark and come down onto it.' },
    delivered: { id: 'delivered', text: 'Delivery confirmed.' },
    'delivered-a': { id: 'delivered-a', text: 'First delivery confirmed. Two more remain.' },
    'delivered-b': { id: 'delivered-b', text: 'Second delivery confirmed. One final package.' },
    'delivered-c': {
      id: 'delivered-c',
      text: 'Final delivery confirmed. All emergency supplies have reached their destinations.',
    },
    // Said after a delivery that is NOT the last: the pilot has to go back for
    // the next box rather than on to the next mark.
    back: { id: 'back', text: 'Return to the logistics hub for the next package.' },
    'back-a': {
      id: 'back-a',
      text: 'Return to the logistics hub. Package B is waiting on the pad.',
    },
    'back-b': { id: 'back-b', text: 'Back to the hub once more. Package C is the last one.' },
    home: { id: 'home', text: 'All deliveries are complete. Return to the hub and land safely.' },
    landing: { id: 'landing', text: 'The pad is right below you. Bring it down gently.' },
    complete: {
      id: 'complete',
      text: 'Excellent work, pilot. All three deliveries completed successfully.',
    },
  },

  // All four points first, then the flying. Every finished run scores at least
  // three, so what separates the ratings is whether the city was flown cleanly
  // and whether the round trips were flown briskly.
  ranks: [
    {
      stars: 3,
      text: 'All 3 delivered and home, no crashes, inside 7:00',
      test: (r) =>
        r.delivered && r.landed && r.points >= GOLD && r.collisions === 0 && r.timeSec <= 420,
    },
    {
      stars: 2,
      text: 'All 3 delivered and home, one crash at most',
      test: (r) => r.delivered && r.landed && r.points >= SILVER && r.collisions <= 1,
    },
    {
      stars: 1,
      text: 'Deliver all three packages and land back at the hub',
      test: (r) => r.delivered && r.landed,
    },
  ],
};
