import type { MissionSpec, Vec3 } from '@shared/types';

// ----------------------------------------------------------------------------
// The mission content model.
//
// A mission is pure data, the way a lesson is: a route, three zones, the tests
// that open and close them, and the lines Mission Control says. It never touches
// the engine — `MissionDirector` walks it and `missionStore` holds the live
// state, so the same shape can describe a second mission without a second
// runtime.
//
// It deliberately does NOT reuse `Lesson`. A lesson is Explain -> Demonstrate ->
// Practice -> Reward and carries a demo timeline, a validator and a star rubric
// keyed to one drill. A mission has none of those phases; what it shares with a
// lesson is the CHECKPOINT — and that piece is shared for real, through
// `CheckpointSphere`, which both draw.
// ----------------------------------------------------------------------------

/** Which leg of the flight a checkpoint belongs to. */
export type MissionLegId = 'toPickup' | 'toDrop' | 'toBase';

/**
 * One optional scoring point on the route, worth exactly one point.
 *
 * OPTIONAL is the whole design. The brief says the pilot decides how to fly
 * between the buildings, so a checkpoint that gated the next leg would quietly
 * turn the city into a corridor. A checkpoint the pilot flies past is a point
 * not taken — never a failure, never a block — which is what lets a suggested
 * line and free navigation live in the same mission.
 */
export interface MissionCheckpoint {
  id: string;
  /** Shown in the HUD as the next one along: 'A1', 'B3'. */
  label: string;
  /** Centre of the scoring sphere, world metres. */
  at: Vec3;
  /** How close the drone's centre must get, in metres. Also the visual trigger:
   *  `CheckpointSphere` draws the ball inside this, so what you can see is what
   *  you fly into. */
  reach: number;
  /** Radius of the drawn ball. Smaller than `reach` so the light sits wholly
   *  inside the volume that scores. */
  radius: number;
  leg: MissionLegId;
  /**
   * Whether the payload is GATED on this one. Default true.
   *
   * Precision Delivery makes every ring required: the package will not release
   * until they are all taken, which is what turns a scattering of bonuses into a
   * route. Forest Fire cannot do that — its brief asks for a pilot who picks
   * their own way through the trees — so its rings are pure guidance and pure
   * score, and skipping the lot still lets the tank open over the fire.
   */
  required?: boolean;
}

/** The three mandatory zones: where the package is, where it goes, where home is. */
export type MissionZoneKind = 'pickup' | 'drop' | 'base';

/**
 * A place on the ground the mission cannot move past.
 *
 * Unlike a checkpoint this is a volume with a HEIGHT BAND and a settle test, not
 * a sphere to fly through — a package is picked up and put down by a drone that
 * is over the mark and slow, which is a different question from "did you pass
 * through here".
 */
export interface MissionZone {
  kind: MissionZoneKind;
  /** Ground position, world metres. The mark is drawn on the deck at `groundY`. */
  at: readonly [number, number];
  /** What the HUD calls it. */
  label: string;
  /** How far off centre, horizontally, still counts. */
  radius: number;
  /** Altitude band above the ground that counts, in metres. */
  band: { min: number; max: number };
  /** Ceiling on horizontal speed while the test is being held, m/s. */
  maxGroundSpeed: number;
  /** Ceiling on climb/descent rate while the test is being held, m/s. */
  maxVerticalSpeed: number;
  /** Seconds every condition must hold together before the zone fires. */
  hold: number;
  /**
   * The ground height under THIS mark, when it is not the mission's own.
   *
   * New York is a flat plane and one `groundY` describes all three of its zones.
   * The forest is not: its clearing is at zero and the hollow the fire burns in
   * is twelve and a half metres below it (measured — see
   * `scripts/check-forest-route.mjs`). A height band judged against the
   * clearing would ask the pilot to hover under the terrain.
   *
   * Measured, never guessed. The forest map has no `groundY` in its spec at all,
   * precisely because it has no single ground height.
   */
  groundY?: number;
  /**
   * The VISIBLE surface this mark's deck stands on, when the deck is a
   * structure rather than the building itself.
   *
   * New York's colliders are generated by merging same-band cells into
   * rectangles and filling each one to the TALLEST thing inside it, so a roof
   * with a parapet is solid all the way up to the parapet: `groundY` there is a
   * metre above the slab a pilot can see, and the drone rests on an invisible
   * box rather than on the roof. A mark drawn at `groundY` on such a roof hangs
   * in mid-air, which is precisely how it looked.
   *
   * The gap is FILLED. `MissionMarkers` draws a delivery platform from `padBase`
   * up to `groundY` and `RooftopPadCollider` makes it solid, so the mark is
   * painted on something the aircraft really stands on. (The city colliders have
   * since been fitted to the slab rather than the parapet; the platform now
   * carries its own collider instead of hiding one.)
   *
   * Measured off the GLB, never guessed:
   *
   *     node scripts/check-roof-marks.mjs
   *
   * Absent on a mark that stands on the ground it is drawn at, which is every
   * mark on every other mission.
   */
  padBase?: number;
  /**
   * How far over this mark's deck the ring is drawn, metres. Defaults to 3 cm,
   * which is a value for FLAT ground: it only has to clear the road surface so
   * the two do not z-fight.
   *
   * A mark on uneven ground needs more. The forest's landing pad sits on a road
   * with half a metre of undulation along it, and at 3 cm the ring was UNDER the
   * ground it was painted on from any low approach: a rise a few metres out
   * covered it, so the mark the pilot is coming home to disappeared from some
   * headings and came back on others. Raised, it clears the lip and stays one
   * ring from every direction, which is the whole job of the thing.
   */
  ringLift?: number;
}

/** One rung of the mission's rating, best first. */
export interface MissionRank {
  stars: 1 | 2 | 3;
  /** What it takes, in the pilot's words — shown before the flight and after. */
  text: string;
  test: (r: MissionResult) => boolean;
}

/** What a finished attempt is judged on. */
export interface MissionResult {
  points: number;
  maxPoints: number;
  timeSec: number;
  collisions: number;
  delivered: boolean;
  landed: boolean;
}

/**
 * One beat of the mission, for the briefing card's flow row.
 *
 * The shape of the job before any of the prose: four words that say what this
 * mission IS. A card that opens with four paragraphs makes the pilot read to
 * find that out, and most of them will not — the flow answers it in a glance and
 * lets the prose be what it should be, the detail underneath.
 *
 * Written by the mission rather than derived from the legs: the state machine's
 * names are engineering ('carrying', 'toDrop'), and a briefing should read like
 * a job sheet.
 */
export interface MissionStep {
  /** One word, upper-cased on screen: 'Collect', 'Carry'. */
  label: string;
  /** A few words under it, in the pilot's language. */
  note: string;
  /**
   * Which picture the briefing draws over this beat.
   *
   * A KEY, not an image path. The briefing card wants a thumbnail per step and
   * this app has no image assets at all — `src/assets` is models and nothing
   * else, and a strict CSP means a texture cannot be fetched from anywhere. So
   * each beat names a small scene the card draws in SVG: the package on its lit
   * mark, the drone threading the towers, the tank open over the fire. Drawn
   * rather than photographed also means they stay right when a mission's numbers
   * move, which a screenshot would not.
   */
  art: MissionArt;
}

/** The scenes the briefing card knows how to draw. */
export type MissionArt = 'collect' | 'city' | 'forest' | 'deliver' | 'suppress' | 'land';

/** A line from Mission Control, played once when its leg begins. */
export interface RadioLine {
  /** Store key, so a line can never be played twice. */
  id: string;
  text: string;
}

/**
 * What KIND of job the mission is, which is the one thing the runtime branches
 * on.
 *
 * 'delivery' puts something down on a mark. 'suppression' holds a position over
 * a target while a tank empties into it. They share the whole of the rest of the
 * mission — collect, carry, come home, land — and they share the zone that
 * judges the middle of it: in both cases the pilot has to be centred, at the
 * right height and stopped. What differs is how long, and what the holding is
 * FOR.
 */
export type MissionKind = 'delivery' | 'suppression' | 'search';

/**
 * One of the places the casualty can be, on a SEARCH mission.
 *
 * Three are authored and exactly one is live per attempt, chosen when the
 * attempt arms. The other two are ordinary city: no beacon, no signal, nothing
 * to find. That is what stops the mission being memorised — and it is why the
 * live one is an INDEX held in the store rather than a field on the mission,
 * the same way a multi-point delivery's live package is.
 *
 * Where the pilot is told to look is NOT here either. It is the RED ZONE, drawn
 * round whichever site is live and held in the store for the attempt — see
 * `searchZone.ts`. No string in the mission names a position.
 */
export interface MissionSearchSite {
  /** Short id, for the run-specific radio keys and the tests. */
  id: string;
  /** Where the casualty is, world metres. */
  at: readonly [number, number];
  /** The rescue zone, revealed only once the signal is confirmed. `kind` is
   *  'drop': it is the middle of the mission, and giving it a fourth zone kind
   *  would mean two marks describing one hover. */
  zone: MissionZone;
}

/**
 * The search, on a search mission.
 *
 * Only the numbers the runtime needs. Where the casualty is, is one of `sites`;
 * how the pilot is told they are close, is the three radii below.
 */
export interface MissionSearch {
  /** The candidate locations, one per compass direction. One is live per
   *  attempt. */
  sites: readonly MissionSearchSite[];
  /**
   * Metres at which the signal is first heard at all, and the outer edge of the
   * readout.
   *
   * Beyond this the HUD says NOTHING — not a weak reading, not a zero. A signal
   * cell sitting at 0% across the whole map is a cell the pilot learns to
   * ignore, and worse, one they can fly a grid against: watch for it to leave
   * zero and you have a detector that works at any range.
   */
  detectRadius: number;
  /** Metres at which the location is CONFIRMED and the rescue zone is revealed.
   *  The pilot has to have flown to it, not merely near it. */
  confirmRadius: number;
  /** Height above the deck the beacon's smoke and light stand to, metres. What
   *  makes the site findable by eye rather than by the readout. */
  beaconHeight: number;
  /**
   * How wide the RED ZONE is, metres.
   *
   * The search area drawn on the map, and the only thing the pilot is told
   * about where the casualty is. It replaced four written clues: a paragraph
   * describing a place is a reading test to be solved while flying, and a
   * circle is the same information in the language the map already speaks.
   *
   * Sized so that flying to it is not the mission. A zone the pilot can see
   * across in one hover is a marker with a wide border; one that covers a third
   * of the city has narrowed nothing. See `searchZone.ts` for where inside it
   * the casualty falls.
   */
  zoneRadius: number;
  /**
   * The highest the aircraft may be, metres above the deck, for the signal to
   * be heard or the casualty confirmed at all.
   *
   * Both radii are FLAT — horizontal distance to the site, altitude ignored —
   * because a search is a search of the ground and a pilot who has drifted two
   * metres up should not lose the reading. But flat with no ceiling means a
   * pilot at the aircraft's 30 m limit, looking down on the whole city from
   * above every roof, gets the same detection as one threading the street the
   * casualty is actually in. That is the opposite of what this mission teaches:
   * it turns "search the sector by eye" into "climb until everything is in
   * range".
   *
   * So the search has a roof, and it sits just above the confirmation hover's
   * own band — high enough that arriving from above is normal flying, low
   * enough that the pilot has to come down among the buildings to find anyone.
   */
  maxDetectAgl: number;
}

/**
 * The fire, for a suppression mission.
 *
 * Only the numbers the runtime needs. Where it burns is the `drop` zone — the
 * mission has exactly one place in the middle it must get to, and giving the
 * fire a fourth zone would mean two marks, two radars and two sets of release
 * conditions describing one hover.
 */
export interface MissionFire {
  /** Seconds of unbroken, correctly positioned hover that puts the fire out.
   *  The whole point of the mission: a fire that went out on contact would be a
   *  marker to touch rather than a position to hold. */
  suppressSec: number;
  /** How far off centre the drone can drift before suppression is INTERRUPTED,
   *  in metres. Wider than the zone's own radius: losing the hold is a warning
   *  and a pause, not a reset, and a boundary the pilot bounces in and out of
   *  every second would be unflyable. */
  breakRadius: number;
  /** Radius of the burning ground, metres — what the fire and its scorch mark
   *  are drawn at. Bigger than the hover zone, which sits inside it. */
  burnRadius: number;
  /**
   * How low over the fire's own deck the aircraft may go before it LOSES the
   * tank, in metres. Optional: a fire that does not declare it cannot take the
   * load off anybody.
   *
   * The suppression band starts at a height for a reason — the drone is meant to
   * be over the fire, not in it — and until now dropping below the band simply
   * stopped the hold timer, so a pilot could sit a metre off the burning ground
   * with the tank happily slung underneath and nothing at all happening. This is
   * the honest answer: down there the slings go, the tank falls into the fire,
   * and the attempt is over. It only bites inside the fire's own break radius,
   * so a low pass anywhere else on the map costs nothing.
   */
  loseLoadAgl?: number;
}

/**
 * One package in a MULTI-POINT delivery: what it is, and where it has to go.
 *
 * A mission with this list is flown as a loop rather than as a line — collect,
 * carry, place, come back for the next one — and the loop is the whole job. It
 * is deliberately NOT a second mission runtime: `MissionDirector` walks the same
 * seven legs it already had, and the only thing that changed is that the
 * delivery leg can send the pilot back to the pickup instead of home.
 *
 * A mission without the list is a single delivery and reads `zones.drop`, which
 * is what Precision Delivery and Forest Fire still do.
 */
export interface MissionDelivery {
  /** Short id, used for the run-specific radio keys: 'a' -> `pickup-a`. */
  id: string;
  /** What the HUD and the banners call it: 'Package A'. */
  name: string;
  /** What is inside it, for the briefing and the pickup banner. */
  cargo: string;
  /** Where it goes. `kind` is 'drop', and on a rooftop it carries its own
   *  `groundY` — the height band is judged against the DECK the package is put
   *  down on, and a roof twenty-five metres up is not the street. */
  zone: MissionZone;
  /**
   * Bare waypoints for the run out to this destination, exactly as `homeVia` is
   * for the flight back.
   *
   * They score nothing, draw nothing and gate nothing — the pilot picks their
   * own line. They exist so the route check measures a corridor a drone can
   * actually fly: over this city the straight line from the hub to either roof
   * runs down the middle of a block, so a check on that line would be measuring
   * a flight nobody should make and would fail on scenery the pilot was never
   * going to hit.
   */
  via?: readonly (readonly [number, number])[];
}

export interface Mission {
  id: string;
  /** 1-based position in the mission list, and what the card and the in-flight
   *  badge call it: "MISSION 1". Also drives unlock order, the way a lesson's
   *  `order` does — the list is a path you work along, not a menu. */
  order: number;
  name: string;
  /** One short line under the name on the card. */
  subtitle: string;
  /** Delivery or suppression. Drives the runtime's middle leg, the HUD's
   *  wording and the result sheet — nothing else. */
  kind: MissionKind;
  /** Environment the mission is flown in. */
  envId: string;
  /** One-line summary for the mission card. */
  blurb: string;
  /**
   * The situation, in two or three sentences, told rather than instructed.
   *
   * The WHY, and the first thing on the card. The HOW used to sit beside it as
   * four paragraphs of `briefing` prose; it is gone, because nobody read it. A
   * pilot arrives at this card wanting to fly, and what they take in is the
   * story, the four beats and the objectives — so those three now have to carry
   * the mission on their own.
   */
  story: string;
  /** The job as four numbered lines, one per beat of `flow`. Whole sentences,
   *  in the pilot's language — this is the part of the card most pilots read
   *  instead of the prose. */
  objectives: readonly string[];
  /** A few words under the map's name: what is out there. */
  mapNote: string;
  /** The job in four beats, shown as a numbered row above the briefing. */
  flow: readonly MissionStep[];
  /** Seconds before the mission times out. */
  timeLimitSec: number;
  /** Seconds under which a flight counts as fast, for the top rating. */
  parTimeSec: number;
  /** The flat ground height of this map — zones are drawn and judged from it. */
  groundY: number;
  /**
   * How high the aircraft may fly on this mission, metres. Omitted on every
   * mission that is happy with the airframe's own limit.
   *
   * It can only ever RAISE the ceiling — `FlightScene` ignores a value below
   * the drone's own — because a mission that quietly clipped the aircraft's
   * envelope would be a mission the pilot cannot tell from a broken drone.
   */
  ceiling?: number;
  /** Height the route checkpoints hang at, for the marker and the HUD. */
  routeAltitude: number;
  /** Points needed for each rating. The SAME numbers the rungs below test, so
   *  the registry's summary of this mission and the mission itself cannot drift:
   *  `ranks` reads them rather than repeating them. */
  medals: { bronze: number; silver: number; gold: number };
  /** The fire, on a suppression mission. Absent on a delivery. */
  fire?: MissionFire;
  /** The search, on a search mission. Absent on every other kind. */
  search?: MissionSearch;
  /**
   * Hide every piece of target guidance until the mission says the target has
   * been FOUND.
   *
   * A flag rather than an absence, and that is the whole reason it exists. The
   * marks, the radar dot, the DISTANCE readout and the in-picture pointer are
   * all drawn by DEFAULT — a mission that simply declines to fill in a
   * destination gets them pointing at whatever the shared runtime falls back to,
   * and the next change to any of those four components quietly restores the
   * guidance with nothing failing. An absence cannot be tested. This can, and
   * TC-401 does.
   *
   * Off everywhere but Search & Rescue, which is the only mission whose job is
   * to work out where the destination is.
   */
  hideGuidanceUntilFound?: boolean;
  /**
   * How much of the THROTTLE this mission gives the pilot, 0.1 to 2.
   *
   * Missions fly a softened stick (`MISSION_COMMAND_SCALE`) so the aircraft can
   * be placed to the metre. That is right for roll, pitch and yaw. On the
   * throttle it is not: the number scales the RATE the axis moves at rather than
   * capping the descent, so a soft mission does not come down more gently, it
   * takes twice as long to ask. A mission that spends its time descending onto
   * marks — three collections and three placements — reads that as an aircraft
   * ignoring the stick.
   *
   * Above 1 is allowed, and only here: the sticks are capped at the aircraft's
   * own rate because more would be a different aircraft, but the throttle number
   * is how fast the AXIS travels rather than how fast the drone descends. Asking
   * sooner is not flying faster.
   *
   * Unset means "the same as the sticks", which is what every mission did before
   * this existed and what Precision Delivery and Forest Fire still do.
   */
  throttleScale?: number;
  /**
   * The packages, on a MULTI-POINT delivery. Absent on a single-drop mission.
   *
   * The order is the order they are flown, and it cannot be skipped: the runtime
   * holds one index into this list and only ever advances it by completing the
   * delivery it is on. `zones.drop` on such a mission is the FIRST entry's zone
   * — the same object, not a copy — so anything that still reads `zones.drop`
   * without asking which run is live gets the opening one rather than nothing.
   */
  deliveries?: readonly MissionDelivery[];
  /**
   * The mission ENDS at the drop mark, with no flight home and no landing.
   *
   * Off by default: a delivery is not finished until the aircraft is back on the
   * pad, and the return leg is half of what the pilot is being taught. A
   * suppression mission is a different job. The fire going out IS the outcome,
   * and Forest Fire's brief ends there — so the run is scored the moment the
   * last of the tank goes in, over the hollow, rather than making the pilot fly
   * ninety-five metres back through the trunks to prove something the crossing
   * already proved on the way out.
   *
   * What it changes: the `delivered` -> `returning` -> `landing` tail of the
   * state machine is skipped, `maxPointsOf` drops the landing point, and the
   * result carries `landed: false` honestly rather than claiming a touchdown
   * that never happened. The base zone stays in the spec — it is still where the
   * drone spawns and what `strayRadius` is measured from.
   */
  endsAtDrop?: boolean;
  /**
   * How far from the base a pilot may stray before the mission calls them back,
   * in metres, measured flat from the base zone. Optional, and unset on a
   * mission that does not want it: a bound nothing declares is a bound nothing
   * enforces.
   *
   * It is a WARNING with a grace period, not a wall — see `STRAY_GRACE_SEC` in
   * the Director. A forest has no streets to keep the route honest, so a pilot
   * who has lost the fire can fly the whole map away from it and time out with
   * nothing on screen ever saying they were going the wrong way.
   */
  strayRadius?: number;
  /**
   * Let a live zone's column of light draw THROUGH the scenery.
   *
   * Off by default, and it has to be: over a city the mark is on a street with
   * buildings between it and the pilot, and a light that ignores them is a
   * column hanging in front of a block it is actually behind — the pilot reads
   * a clear line to a mark that has a tower across it.
   *
   * A forest is the case that wants it. It is a wall of trunks with a canopy
   * over it, so a depth-tested light is behind a tree from most of the headings
   * a pilot can be on: the mark vanishes and comes back as they yaw, which reads
   * as a bug rather than as an occlusion. Nothing there is a building, so
   * nothing is misread as a route.
   */
  seeThroughMarks?: boolean;
  route: readonly MissionCheckpoint[];
  /** Bare waypoints for the flight home: the line a sensible pilot takes from
   *  the drop back to the pad. They score nothing and draw nothing — the return
   *  leg is a flight, not a collection — and exist so `check-mission-route` can
   *  measure a corridor that is actually flown rather than the straight line
   *  from the drop to the pad, which cuts through two blocks. */
  homeVia: readonly (readonly [number, number])[];
  zones: Record<MissionZoneKind, MissionZone>;
  radio: Record<string, RadioLine>;
  ranks: readonly MissionRank[];
}

/**
 * The mission as the plugin registry sees it.
 *
 * Derived rather than written twice. The registry is the app's content index —
 * every drone, map and lesson is reachable through it — and a mission that is
 * only reachable through its own module is a mission the rest of the engine
 * cannot be told about.
 */
export function toMissionSpec(m: Mission): MissionSpec {
  return {
    id: m.id,
    name: m.name,
    type: m.kind === 'delivery' ? 'delivery' : 'rescue',
    description: m.blurb,
    medalThresholds: m.medals,
  };
}

/**
 * The checkpoints that have to be taken before the package will release.
 *
 * Everything on the way OUT: the run to the pickup and the carry itself. The
 * return leg's are not in here and cannot be — they come after the delivery, so
 * requiring them would make the mission impossible.
 *
 * This is what turns a scattering of optional bonuses into a route the package
 * has to travel. The pilot still picks their own line between them; what they
 * cannot do is skip the city and go straight to the mark.
 */
export function requiredCheckpoints(m: Mission): readonly MissionCheckpoint[] {
  return m.route.filter(
    (c) => c.required !== false && (c.leg === 'toPickup' || c.leg === 'toDrop'),
  );
}

/** How many of those are still outstanding. */
export function requiredLeft(m: Mission, collected: Record<string, true>): number {
  return requiredCheckpoints(m).filter((c) => !collected[c.id]).length;
}

/**
 * The one place that answers "where now".
 *
 * The lit ring in the world, the radar dot and the DISTANCE readout all come
 * from here, so they can never disagree — one ring is lit over the city and it
 * is the one the dial is pointing at.
 *
 * The rule is ROUTE ORDER, and it is ABSOLUTE: the first ring on this leg that
 * has not been taken, whether or not the drone has already flown past it.
 *
 * It was "the nearest outstanding one" while every ring was lit at once, which
 * let a pilot who skipped one be sent to whichever was now cheapest. With one
 * ring lit at a time that rule turns the route into a thing that jumps around
 * as the drone moves — the lit ball would change under the pilot mid-approach.
 *
 * There was then a middle version that dropped an OPTIONAL ring once the drone
 * was closer to the mark than the ring was, on the theory that a pilot who took
 * their own line should not be sent backwards. What it actually did was let the
 * route be skipped by flying: miss F2, keep going, and F3 lights up — so the
 * chain of marks the pilot is following silently loses a link, and the pilot
 * never learns they missed one until the score comes up short. A ring that
 * disappears because you flew past it is not guidance, it is a reward for
 * ignoring it.
 *
 * So a missed ring STAYS lit until it is flown through. That is a real cost: it
 * points backwards at a ring behind the drone, which on Forest Fire means the
 * arrow can send a pilot back through the trees. That is the intended trade —
 * the rings are still OPTIONAL TO SCORE, and a pilot who wants to write one off
 * simply flies on and eats the point. What they no longer get is a route that
 * quietly re-writes itself around the ring they dropped.
 */
export function nextCheckpointOf(
  m: Mission,
  leg: 'toPickup' | 'toDrop' | 'toBase' | null,
  collected: Record<string, true>,
): MissionCheckpoint | null {
  if (!leg) return null;
  // Required or optional makes no difference to the guidance: the lit ring is
  // the next one in the route's own order, and a mission whose rings are all
  // optional (Forest Fire) is a route like any other.
  return m.route.find((c) => c.leg === leg && !collected[c.id]) ?? null;
}

/** The same answer as a world position, for the radar and the DISTANCE
 *  readout. Null once the leg's rings are all taken, and the caller falls back
 *  to the mark itself. */
export function nextTargetOf(
  m: Mission,
  leg: 'toPickup' | 'toDrop' | 'toBase' | null,
  collected: Record<string, true>,
): readonly [number, number, number] | null {
  return nextCheckpointOf(m, leg, collected)?.at ?? null;
}

/**
 * Points available: every ring on the way out, plus the delivery, plus the
 * landing on a mission that has one.
 *
 * The PICKUP scores nothing. It is not an achievement, it is the start of the
 * job — the mission has not begun until the package is on board, and a point
 * for collecting it made the score say a pilot was one sixteenth of the way
 * through a delivery they had not flown a metre of. What the score counts is
 * the rings, then putting the package down, then getting home.
 */
export function maxPointsOf(m: Mission): number {
  return m.route.length + deliveryCount(m) + (m.endsAtDrop ? 0 : 1);
}

/**
 * The rescue zone the pilot is being judged against right now.
 *
 * The same shape of answer `dropZoneOf` gives a multi-point delivery, and for
 * the same reason: the mission holds the candidates, the store holds which one
 * is live, and everything that draws or tests a mark comes through here so no
 * two of them can disagree about which site the attempt is on.
 *
 * A mission with no `search` answers with its ordinary drop, so this is safe to
 * call anywhere.
 */
export function rescueZoneOf(m: Mission, siteIndex: number): MissionZone {
  return searchSiteOf(m, siteIndex)?.zone ?? m.zones.drop;
}

/** The live site, or null on a mission that is not a search. */
export function searchSiteOf(m: Mission, siteIndex: number): MissionSearchSite | null {
  const list = m.search?.sites;
  if (!list || list.length === 0) return null;
  return list[Math.min(Math.max(siteIndex, 0), list.length - 1)];
}

/** How many packages this mission puts down. One, unless it says otherwise. */
export function deliveryCount(m: Mission): number {
  return m.deliveries?.length ?? 1;
}

/**
 * The drop zone the pilot is being sent to right now.
 *
 * The ONE place that answers it. The Director, the marks, the radar, the
 * DISTANCE readout and the package itself all come through here, so a
 * multi-point mission can never have the arrow on one roof and the release test
 * running against another. Clamped rather than allowed to run off the end: the
 * index is advanced on the frame the last package is delivered, and for the rest
 * of that flight home the answer should be the mark it was just put on.
 */
export function dropZoneOf(m: Mission, runIndex: number): MissionZone {
  const list = m.deliveries;
  if (!list || list.length === 0) return m.zones.drop;
  return list[Math.min(Math.max(runIndex, 0), list.length - 1)].zone;
}

/** The package being carried on this run, or null on a single-drop mission. */
export function deliveryOf(m: Mission, runIndex: number): MissionDelivery | null {
  const list = m.deliveries;
  if (!list || list.length === 0) return null;
  return list[Math.min(Math.max(runIndex, 0), list.length - 1)];
}

/**
 * Every ground mark the mission has, including each package's own destination.
 *
 * Written for the things that have to reason about ALL of them at once — the
 * marks that are drawn, and the deck a dropped box comes to rest on. `zones` is
 * a record of three and cannot grow, so this is the honest list.
 */
export function allZonesOf(m: Mission): readonly MissionZone[] {
  const drops = m.deliveries?.map((d) => d.zone) ??
    m.search?.sites.map((s) => s.zone) ?? [m.zones.drop];
  return [m.zones.pickup, ...drops, m.zones.base];
}

/** The rating an attempt earns: the best rung it passes, or one for finishing. */
export function rankFor(ranks: readonly MissionRank[], r: MissionResult): 1 | 2 | 3 {
  for (const rank of ranks) if (rank.test(r)) return rank.stars;
  return 1;
}

/**
 * The ground height under one zone.
 *
 * The mission's own, unless the zone carries its own — which only the forest
 * needs, and only because its fire burns in a hollow twelve metres below the
 * clearing it launches from. Read through this everywhere rather than through
 * `mission.groundY` directly: a height band measured against the wrong deck is
 * a hover the pilot cannot reach, and it fails silently.
 */
export function zoneGroundY(m: Mission, zone: MissionZone): number {
  return zone.groundY ?? m.groundY;
}

/**
 * How tall the beacon's plume stands at a given site, metres.
 *
 * A RULE rather than a second number to keep in step with the first. The plume
 * has to finish below the hover the pilot is about to hold, or the mission ends
 * with the aircraft inside its own smoke — and on the rooftop site the whole
 * hover band is 3.5 m tall, because the deck is already 25 m up and the
 * aircraft's ceiling is 30. Tying the plume to the band means the roof gets a
 * short flare and the streets keep their full column without either being
 * written down twice.
 */
export function beaconHeightFor(m: Mission, zone: MissionZone): number {
  const wanted = m.search?.beaconHeight ?? 10;
  return Math.min(wanted, zone.band.min * 0.8);
}

/** Horizontal distance between a point and a ground mark, in metres. */
export function flatDist(p: { x: number; z: number }, at: readonly [number, number]): number {
  return Math.hypot(p.x - at[0], p.z - at[1]);
}
