// GENERATED FILE — do not edit by hand.
// Regenerate with:  node scripts/generate-supermarket-plan.mjs
//
// The Supermarket seen from above, for the mission map. Two grids, each
// run-length encoded as [value, count] byte pairs, base64. See the generator
// for how each cell is found.
//
// OUTSIDE — 328 x 219 cells of 0.5 m over the whole map. 0 no ground,
// 1 asphalt, 2 paving, 3 grass, 4 road paint; 5 and up, something
// standing (v - 5) / 10 m tall. 23812 asphalt, 6491 paving,
// 15946 grass, 214 paint, 15125 standing, 10244 without ground.
//
// FLOOR — 252 x 163 cells of 0.25 m over the inside of the store: the
// colliders cut between 0.25 and 2 m. 0 not inside, 1 open floor,
// 2 and up an obstacle (v - 2) / 10 m tall. 24282 open, 241 enclosed
// and filled in.

export const SUPERMARKET_PLAN = {
  outside: {
    x0: -89.5,
    z0: -53.5,
    cell: 0.5,
    w: 328,
    h: 219,
    /** Values from here up are standing structures. */
    struct: 5,
    /** The tallest thing on the plan, metres — the top of the shading ramp. */
    tallest: 8.3,
    data:
    'AP8AXB0BAyMArAM6HQEDBh0BAwQAMQMlAKwDRwAvAyYArANIAC0DJh0BAKwDSQArAygArANKACkDKQCsA0sAJwMqAKwDTAAl' +
    'AysArANNACMDLACsA04AIQMtAKwDTwAfAy4ArANQAB0DLwCsA1EAGwMwAKwDUgAZAzEArANTABcDMgCsHAEDUwAVAzMArANV' +
    'ABMDNACsA1YAEQM1AKwDVwAPAzYAIkE2AFQDWAANAyQWAgMFFgEDARYBAwkAIEE6AFIDBBYBAwUWAgMDFgEDAhYBAwMWAQMC' +
    'FgEDCxYBAwIWAQMDFgEDBhYBAwIWAQMDFgEDHgAMAxQAQkE8AJYDFAAMAxQAQEFAAJQXAQMTAAwDFAAhGAQAARgWAANBQgAZ' +
    'Ag4AbAMUAAwDFAAeAgFBegABAg4AbAMUAAwDFAAeAgFBegABAg4AbAMUAAwDFAAeGAFBegABAgsyAwBsAxQADAMTFwEAHhgB' +
    'QXoAAQIGMgsAaQMUAAwDFAAdGAJBegABAgMyEABnAxQADAMUAB0YAkF6MhUAZhcBAxMADAMUAB4CAUF6MgsCBDIHAGUDFAAM' +
    'AxQAHRgCQXoyCQIFQTEAPAMUAAwDFAAdGAJBejIGAghBMQI8AxQADAMUAB0YAkF6MgICDEExAjwDFAAMAxQAHRgCQXoAAQIN' +
    'QTECPAMUAAwDFAAdGAJBBkMEQRNDBUETQwRBE0MFQRNDBEESAAECDkEwAjwDFAAMAxQAHRgCQQZDBEETQwVBE0MEQRNDBUET' +
    'QwRBEgABAg5BMAI8AxQADAMUAB0YAkEGQwRBE0MFQRNDBEETQwVBE0MEQRIAAQIOQTACPAMUAAwDFAAdGAJBBkMEQRNDBUET' +
    'QwRBE0MFQRNDBEESAAECDkEwAjwDFAAMAxQAHRgCQQZDBEETQwVBE0MEQRNDBUETQwRBEgABAg5BMAI8AxQADAMUAB0YAkF6' +
    'AAECDkEwAjwDFAAMAxQAHRgCQXoAAQIOQTACPAMUAAwDFAAdGAJBegABAg5BMAI8AxQADAMUAB0YAkF6AAECDkEwAjwDFAAM' +
    'AxQAHRgCQXoAAQIOQTACPBcBAxMADAMUAB0YATgBQXo4AQIOQTACPAMUAAwDFAAeAgFBegABAg5BMAI8AxQADAMUAB0YAkF6' +
    'AAECDkEwAjwDFAAMAxQAHRgCQXoAAQIOQTACPAMUAAwDFAAdGAJBegABAg5BMAI8AxQADAMUAB0YAkESQwRBE0MFQRNDBEET' +
    'QwVBE0MEQQYAAQIOQTACPAMUAAwDFAAdGAJBEkMEQRNDBUETQwRBE0MFQRNDBEEGAAECDkEwAjwDFAAMAxQAHRgCQRJDBEET' +
    'QwVBE0MEQRNDBUETQwRBBgABAg5BMAI8AxQADAMUAB0YAkESQwRBE0MFQRNDBEETQwVBE0MEQQYAAQIOQTACPAMUAAwDFAAd' +
    'GAJBegABAgscA0EwMhwCIAMUAAwDFAAdGAJBegABAgscA0EwMhwCIAMUAAwDFAAdGAJBegABAgscA0EwMhwCIAMUAAwDFAAd' +
    'GAJBeiUCAgwtAUEwMhwCIAMUAAwDFAAdGAJBeiUCAgwtAUEwMhwCIAMUAAwDFAAdGAJBeiUCAgwtAUEwMhwCIBcBAxMADAMU' +
    'AB0YAkF6JQICDC0BQTAyHAIgAxQADAMUAB0YAkF6JQICDC0BQTACPAMUAAwDFAAdGAJBeiUCAgwtAUEwAg4LAQItAxQADAMU' +
    'AB0YAkF6AAECCxwDQTACPAMUAAwDFAAdGAJBegABAgscA0EwAjwDFAAMAxQAHRgCQQZDBEETQwVBE0MEQRNDBUETQwRBEgAB' +
    'AgscA0EwAjwDFAAMAxQAHRgCQQZDBEETQwVBE0MEQRNDBUETQwRBEgABAg5BMAI8AxQADAMUAB0YAkEGQwRBE0MFQRNDBEET' +
    'QwVBE0MEQRIAAQIOQTACPAMUAAwDFAAdGAJBBkMEQRNDBUETQwRBE0MFQRNDBEESAAECDkEwAhMyCAIhAxQADAMUAB0YAkF6' +
    'AAECDkEwAhMyCAIhAxQADAMUAB0YAkF6AAECDkEwAhMyCAIhAxQADAMUAB0YAkF6AAECDkEwAhMyCAIhAxQADAMUAB0YAkF6' +
    'AAECDkEwAg4KAQIEMggCIQMUAAwDFAAdGAJBegABAg5BMAITMggCIQMUAAwDFAAdGAJBegABAg5BMAITMggCIRcBAxMADAMD' +
    'QggDCQAdGAJBegABAg5BMAITMggCIQMUAAwDA0IIAwkAHRgCQXoAAQIOQTACEzIIAiEDFAAMAwNCCAMJAB4CAUF6AAECDkEw' +
    'AhMyCAIhAxQADAMDQggDCQAeAgFBegABAg5BMAITMggCIQMUAAwDA0IIAwkAHgIBQRJDBEETQwVBE0MEQRNDBUETQwRBBgAB' +
    'Ag5BMAITMggCIQMUAAwDA0IIAwkAHgIBQRJDBEETQwVBE0MEQRNDBUETQwRBBgABAg5BMAITMggCIQMUAAwDA0IIAwkCJQAB' +
    'QQtDBEETQwVBE0MEQRNDBUETQwRBBgABAg5BMAITMggCIQMUAAwDA0IIAwkCJQABQQtDBEETQwVBE0MEQRNDBUETQwRBBgAB' +
    'Ag5BMAITMggCIQMUAAwDA0IIAwkCJQABQQtDBEETQwVBE0MEQRNDBUETQwRBBgABAg5BMAITMggCIQMUAAwDA0IIAwkCJQAB' +
    'QXMAAQIOQTACEzIIAiEDFAAMAwNCCAMJAiUAAUFzAAECDkEwAhMyCAIhAxQADAMDQggDCQIlAAFBcwABAg5BMAIOCwECBDII' +
    'AiEDFAAMAwNCCAMJAiUAAUFzAAECDkEwAhMyCAIhAxQADAMDQggDCQIeOAhBczgBAg5BMAITMggCIQMUAAwDA0IIAwkCJQAB' +
    'QXMAAQIOQTACEzIIAiEDFAAMAwNCCAMJAiUAAUFzAAECDkEwAhMyCAIhAxQADAMDQggDCQIlAAFBcwABAg5BMAITMggCIQMU' +
    'AAwDA0IIAwkCJQABQXMAAQIOQTACDgoBAgQyCAIhAxQADAMDQggDCQIlAAFBcwABAg5BMAITMggCIQMUAAwDA0IIAwkCJQAB' +
    'QS0AH0EnAAECDkEwAhMyCAIhAxQADAMDQggDCQIlAAFBLAABIwFBHgABQSYAAQINQTECEzIIAiEDFAAMAwNCCAMJAiUAAUEq' +
    'SgFMAU0CSgRLAUwBTQFPAVABUQFTAVQBVQFXAVgCVgFVAVQBUgFRAVABTgFNAUwBSgRLAU0CSwFBJAABAg1BMQIUDgIPAgoC' +
    'AiIDFAAMAwNCCAMJAiUAC0ESAA5KAUwDSgRLAUwBTQFPAVABUQFTAVQBVQFXAVgCVgFVAVQBUgFRAVABTgFNAUwBSgRLAUwC' +
    'SwEAD0ESAAQCDUExAg4LAQIEGAEyBjEBAiEDFAAMAwNCCAMJAiUEAQIIBAFBAQACQQ8AAhwDAgpBAQICFQQHARUDAgEVAwcB' +
    'FQgCARUDBwIVAwIIBAECCQACQQ8AAkEBAhBBMQITGAEyBjEBAiEDFAAMAwNCCAMJAjBBAQACAgElAUEBRwFNAVMBVQFPAUkB' +
    'QwElAQIBAAJBAhwDAg0VBAcBFQMCAQcMAgEVAwcFAhJBAgACAgElAUMBSQFOAVQBUwFNAUgBQgElAQIBAAJBAQIRQTECExgB' +
    'MgYxAQIhAxQADAMDQggDCQIsBwEiAwIBQQECAiUBQQFHAU0BUwFVAU8BSQFDASUBAgFBAgICHAMCP0ECAgElAUMBSQFOAVQB' +
    'UwFNAUgBQgElAQIBQQICEkExAhMYATEHAiEDFAAMAwNCCAMJAiwHASIDAoEyCAINMgcCHhcBMAYvAQIhAxQADAMDQggDCQIs' +
    'BwEiAwKBMggCDTIHAh4XASwGCQECIQMUAAwDBEIBQQUlAQMJAiwHASIDAoEyCAINMgcCHiQBKAcCIQMUAAwDA0EBQgFBAQMB' +
    'QQMlAQMJBiwCFwQBAgMGFAIPBhYCHQYJAgsyCAINMgcCHhcBIAYRAQIhFwEDEwEKBAEBAQMDQQcmAQMJAS4HARUDAX8yCAEN' +
    'MgcBHhYBHAIdAhwCDwEBIQMUAAwDA0EHJgEDCQEtBAEHARUDBBQBOgQZARgyCAENMgcBHhUBHwEcBQkBASEDFAAMAwNAAUEG' +
    'JgEDCQEuBwEVAwElBAEBRwQBAREyCAENMgcBGQsBAQUVARoEFgEBIgMUAAwDAz8HJQEDCQEhIwEBDAcBFQMBJQQBAUcEAQER' +
    'MggBDTIHAUcDFAAMAwM7ByUBAwgXAQEtBAEHARUDBBQBEQQBASgEGQEGBAEBETIIAQ0yBwFHAxQADAMDIQE1BiwBAwkBLgcB' +
    'FQMBJQQBAUYDAQQBAREyCAENMgcBRxcBAxMADAMDJwEtBiUBAwkBLgcBFQMBJQQBAUcEAQEBBAEBDzIIAQ0yBwFHFwEDEwAM' +
    'AwMlASwFKwEiAQMJAS0EAQcBFQMECwEBBAgBEQQBAQIEAQEDBAEBAwQBAR0EBAEBBBQBBgQBAQEEAQEPMggBDTIHAUcDFAAM' +
    'AwQpASsEJgEDCgFXBAEBRgMBBAEBETIIAQ0yBwFHAxQADAMFKAEpASgBJwEDCwEhCAEBNQQBAQQEAQEDBAEBAwQBAR0DAQEc' +
    'BAEBAQQBAQ8yCAENMgcBRwMUAAwDFAEuBAQBAQQEAQEECwEBBAIBFgQBAQMEAQEDBAEBHAQFAQEEAwEBBA4BBgQBAQEEAQEP' +
    'MggBDTIHAUcDFAAMAxQBQAMBAXAyCAENMgcBGQoBAS0DFAAMAxQBDAgXASQIFwEGCBcBIggUMggBDTIHAQoIFwEJCBcBBgMU' +
    'AAwDFAELCAEDDQgBAwoBIggBAw0IAQMKAQQDBQgBAxIIAQEgAxUyCAENMgcBCQgBAxIIAQMECAEBBwgBAxcIAQEFAxQADAMU' +
    'AQsIAQMYASIIAQMYAQQDGAgBAR8IAQMVMggBDTIHAQkDGAgBAQcIAQMXCAEBBRcBAxMADAMUAQwDCAgBAwEIAQMJCAEDAggB' +
    'ASMDCggBAwkIAQMCCAEBBAgBAxcBIQMNCAEDAQgBAwEIAQMCCAEyCAENMgcBCQgCAxYBCAgCAwcIAQMNCAIBBQMUAAwDFAGx' +
    'MggBDTIHATQDAwEQAxQADAMUAXQIAQE8MggBDTIHARUIAQEeAwMBEAMUAAwDFAFSCAIBGwgBAUEyCAEMEQEyBwEVCAEBHgMD' +
    'ARADFAAMAxMXAQFRCAEDAggBAQIIAQEWAwMBQDIIAQwSATIHAQ0IAQEmAwMBEAMUAAwDFAFRAwMIAQEZAwMBQDIIAQwSATIH' +
    'ATQDAwEQAxQADAMUAVEDAwgBARkDAwENJAEBMjIIAQwSATIHATQDAwEQFwEDEwAMAxQBUQMDCAEBGQMDAQoXARgBHgEoAS0B' +
    'MAExAjIfAQ8yCAEMEgEyBwE0AwMBEAMUAAwDFAFRAwMIAQEZAwMBCRkBHAIgASgBLQEwATEBMiABDzIIAQwQATIHATQDAwEQ' +
    'AxQADAMUAVEDAwgBARkDAwEJGgEcAR0BIQEoAS0BMAExATIgAQ8ZATIGGQEBDQ4CDwIOAgE1AwMBEAMUAAwDFAFRAwMIAQEZ' +
    'AwMBCRoBHAEdASEBKAEtATABMQEyIAEPGQEyAgMBMgMZAQEMFQEyBwE0AwMBEAMUAAwDFAFRAwMIAQEZAwMBCRoBHAEdASEB' +
    'KAEtATABMQEyIAEPGQEyBhkBAQwVATIHATQDAwEQAxQADAMUAVEDAwgBARkDAwEJGgEcAiABKAEtATABMQEyIAEPGQEyBhkB' +
    'AQwVATIHATQDAwEQAxQADAMUAVEDAwgBARkDAwEJFgEJARwBIAEoAS0BMAExATIgAQ8ZATEGGQEBDBUBMQcBNAMDARADFAAM' +
    'AxQBUQMDCAEBGQMDAQsQAREBJAEJBgEBEAESBBEBDwEBJBgBLwYYAQEMDwEwBwE0AwMBEBcBAxMADAMUAVEDAwgBARkDAwFA' +
    'GAErBhgBAQwRASwHATQDAwEQAxQADAMUASQiAQEYCAEBEwMDCAEBGQMDAT8kARgBJgYYASQBAQsbASgHJAEBMwMDARADFAAM' +
    'AxQBJCIBASwDAwgBARkDAwFAFwEdAh4CHQIXAQEMEgEgBh4BATQDAwEQAxQADAMUASQIAgEWCAIBEwMDCAEBGQMDAUAWARwG' +
    'FgEBDBABHAMdARwCGAEBNAMDARADFAAMAxQBIwgBAwIIAQEUAwMIAQESAwMIAQEZAwMBQBQBGgEbBBoBFAEBDR8BHAQfARcB' +
    'ATQDAwEQAxQADAMUASMIAQMDARQDAwgBARIDAwgBARkDAwFBEgEZBBIBAQ4UARoEGQEBNQMDARADFAAMAxQBIwgBAwIIAQEU' +
    'AwMIAQESAwMIAQEZAwMBkAMDARAXAQMTAAwDFAEjCAEDAwEUAwMIAQERAwQIAQEZAwMBkAMDARADFAAMAxQBIwgBAwMBFAMD' +
    'CAEBEgMDCAEBGQMDAZADAwEQAxQADAMUASMIAQMDARQDAwgBARIDAwgBARkDAwGQAwMBEAMUAAwDFAEjCAEDAwEUAwMIAQES' +
    'AwMIAQEZAwMBkAgDARADFAAMAxQBIwgBAwIIAQEUAwMIAQESAwMIAQEZAwMBkQMBAREDFAAMAxQBIwgBAwMBFAMDCAEBEggB' +
    'AwIBGggBAwEIAQGjAxQADAMUASMIAQMDARQDAwgBATUIAQGfAxQADAMUASMIAQMDARQDAwgBAdUDFAAMAxQBIwgBAwMBFAMD' +
    'CAEBGCMBAbwDFAAMAxQBIwgBAwMBFAMDCAEB1QMUAAwDFAEjCAEDAwEUAwMIAQHVAxQADAMUASMIAQMCCAEBFAMDCAEB1QMU' +
    'AAwDFAEjCAEDAwEUCAEDAggBAdUDFAAMAxQBIwgBAwMBFAMDCAEB1QMUAAwDFAEjCAEDAwEUAwMIAQHVAxQADAMUASMIAQMD' +
    'ARQDAwgBAdUDFAAMAxQBIwgBAwMBFAMDCAEB1QMUAAwDFAEjCAEDAwEUAwMIAQHVAxQADAMUASMIAQMDARQDAwgBAdUDFAAM' +
    'AxQBIwgBAwMBFAgBAwIIAQHVAxQADAMVASMDAggBARQIAQMCAdYDFAAMAxQB/wEVAxQADAMUAf8BFQMUAAwDFAH/ARUDFAAM' +
    'AxQB/wEVAxQADAMUAf8BFQMUAAwDFAH/ARUDFAAMAxQB/wEVAxQADAMUAf8BFQMUAAwDFAH/ARUDFAAMAxQB/wEVAxQADAMU' +
    'Af8BFQMUAAwdAQMTAf8BFQMUAAwDFAH/ARUDFAAMAxQB/wEVAxQADAMUAf8BFQMUAAwDFAH/ARUXAQMTAAwDFAH/ARUDFAAM' +
    'AxQB/wEVAxQADAMUAf8BFQMUAAwDFAH/ARUDFAAMAxQB/wEVAxQADAMUAf8BFQMUAAwDFAH/ARUDFAAMAxQB/wEVFwEDEwAM' +
    'AxQB/wEVAxQADAMUAf8BFQMUAAwDFAH/ARUDFAAMAxQB/wEVAxQADAMUAf8BFQMUAAwDFAH/ARUDFAAMAxQB/wEVFwEDEwAM' +
    'AxQB/wEVAxQADAMUAf8BFQMUAAwDFAH/ARUDFAAMAxQB/wEVAxQADAMUAf8BFQMUAAwDJRcBAw4XAQMIFwEDLBcBAwYXAQMH' +
    'FwEDCBcBAxAXAQMZFwEDJBcBA0QXAQMkAA0D/wM7AA8D/wM5ABED/wM3ABMD/wM1ABUD/wMzABcD/wMxABkD/wMvABsD/wMt' +
    'AB0D/wMrAB8D/wMpACED/wMnACMD/wMlACUD/wMjACcD/wMhACkD/wMfACsD/wMdAC0D/wMbAC8D/wMZADEDoR0BAxkdAQMq' +
    'HQEDGR0BAxUAHw==',
  },
  floor: {
    x0: -65,
    z0: -43.75,
    cell: 0.25,
    w: 252,
    h: 163,
    /** The roof's underside: inside and below it, the drone is indoors. */
    ceiling: 6,
    data:
    'AE8ibgCMIgMYARUUGAIVExgCFRQYAhUTGAIVFBgBIgIAiiICAQIYARUUGAIVExgCFRQYAhUTGAIVFBgBAQEiAwCHIgIBAxgB' +
    'FRQYAhUTGAIVFBgCFRMYAhUUGAEBAyICAIQiAgEFGAEVFBgCFRMYAhUUGAIVExgCFRQYAQEEIgMAgSICAS0IAgFJIgIARBIC' +
    'FQIBARUtAQgiAwEvCAEBSiIDAD8VBwEBFS0BByICATEIAgFLIgIAPBUJAQEVLQEFIgMBMwgCAUsiAwA5FQciNwE2CAIBSBAE' +
    'IjAACRUFIgQBNAgBATgIAQFIEAQdCBADAQcSAQoBCAIBARkLAQMdCwAIFQQiAwE2CAIBOAgCAUcQBB0IEAMBBxIBCgEBAxkL' +
    'AQMdCwAHFQQiAgE4CAEBHgoGARYIAgFGEAQdCBADAQcSAgEDGQsBAx0LAAYVBCICATkIAQEeCgYBFwgBAUYQBB0IEAMBCBIB' +
    'CgEBAhkLAQMdCwAGFQMiAgE5CAIBHgoGARcIAgFFEAQdCBADDQELAQoBAQUSAQoBARAdCyIBAAQVBCIBAToIAQEfCgYBGAgC' +
    'AUUNAgENDQQKAgEBEgEKAQEQHQsiAQAEFQMiAgE6CAEBHwoGARkIAQFFDQEBEQ0EEAESAQ0BAQ8dCyIBAAQVAyIBAToIAgE/' +
    'CAEBQwkBDQEBFQ0BEgEMAQ0FAQoQCyIBAAMSARUDIgEBOggBAUAIAgFCDQIBFg4BDAEBAQoDDQUBBhALIgEAAxIBFQIiAgE6' +
    'CAEBQQgCAUAKAQ0BARcOAgwBAQMjEBAGIgEAAxUDIgEBOggCAUIIAQFADAIBGA4BDAEBBR8OEAYhAQADFQMiAQE6CAEBRAgB' +
    'AT4KAQwBARkOAQwBAQUfDhAGIQEAAwEDIgEBOggBAUQIAgE9DAIBGQ4CDAEBBB8OEAYhAQADFQMiAQE5CAIBKQoHARUIAQE8' +
    'CgEMAQEbDgEMAQEEHw4QBiEBAAMVAyIBATkIAQEqCgcBFggBATsMAgEbDgEMAQEEHw4QBiEBAAMVAyIBATkIAQEqCgcBFggC' +
    'ATkLAgEcDgINAQEDHw4QBiEBAAMVAyIBATgIAgEqCgcBFwgCATgLAgEcBQEJAQ0BAQMfDhAGIQEAAxUDIgEBOAgBASsKBwEY' +
    'CAEBOAsBAR4JAQ0BBQEjEBAGIQEAAxUDIgEBOAgBAUoIAgE2CwIBHgkBDQIHAgEOEAYhAQADFQMiAQE3CAIBSwgCATULAQEd' +
    'BQEHAgkBDQEBEBAGIQEAAxUDIgEBNwgBAU0IAQE0DAIBGwUBBwMBAQkBDQEBEB0GIQEAAxUDIgEBNwgBAU4IAQEzDAEJAQEZ' +
    'BQEHAwEDCQENAQELEAUdBiEBAAMVAyIBATYIAgFOCAIBMQwCARgFAQcDAQUJAg0BAQgIAhAFHQYiAQADFQMiAQE2CAEBUAgC' +
    'ATAMAQkBARYHAwEHCgMNAQoJAQEQBR0GAAQVAyIBARgUDwgHCQkIBAE0GRMJBw4aAQEOFgwLHAwJAQEJCgEbCwoBAQEQBR0G' +
    'AAQVAyIBARgUARwNFAEBBwkJAQMICBgJCQEYARUQGAEVEBgBGRMBBggBDgQTBhkNEwIOAQEBDgETAhkCEw8OAgELHAEJChwC' +
    'AQkKARsLCgEBARAFHQYiAQADFQMiAQEYFAEcDRQBAQcJCQELGAkJARgBFRAYARUKGAMVAxgBGRMBBw4DDQETBhkNEwIOAQEB' +
    'DgETARkPEwMOAgELHAEJChwCAQkKARsLCgEBARAFHQYiAQADFQMiAQEYFAEcDRQBAQcJCQELGAkJARgBFRAYARUKGAMVAxgB' +
    'GRMBCA4DEwUZDhMDAQEOARMBGQ8TAw4CAQocAgkKHAEJAQEJCgEbCwoBAQEQBR0GIgEAAxUDIgEBGBQBHA0UAQEHCQkBCxgJ' +
    'CQEYARcQGAEXEBgBGRMBCQ4CEwUZDhMCDgEBAQ4BEwEZDxMDDgIBChwBCQscAQEKCgEbCwoBAQEQBgEFIgEAAxUDIgEBGBQB' +
    'HA0UAQEHCQkBCxgJCQEYARcQGAEXEBgBGRMBCg4DEwMZDhMCDgEBAQ4BEwEZCBMDGQQTAw4CAQocAQkLHAEBCgoBGwsKAQEM' +
    'IgEAAxUDIgEBGBQBHA0UAQEHCQkBCxgJCQEBIxkTAQsOAxMCGQ4TAg4BAQEOARMQDgUBCQkBHAEJCxwBAQoKARsLCgEBDCIB' +
    'AAMVAyIBARgUARwNFAEBBwkJAQsYCQkBASMZEwEMDhUBAQ4FEwQOBBMEDgUBCRwCCQocAgEKCgEbCwoBAQwiAQADFQMiAQEY' +
    'FAEcDRQBAQcJCQELGAkJAQEjGRMBCQwEASgFAQoCAQkcAQkLHAEJAQEKCgEbCwoBAQwiAQADFQMiAQEYFAEcDRQBAQcJCQEL' +
    'GAkJAQEjGRMBBgwEAS0KAwEGCQEcAQkLHAEBCwoBGwsKAQEMIgEAAxUDIgEBGBQBHA0UAQEHCQkBCxgJCQEBIxkTAQMMBAEx' +
    'BQEKAgEFHAIJCxwBAQsKARsLCgEBDCIBAAMVAyIBARgUARwNFAEBBwkJAQsYCQkBASMZEwwEATYJAwEDHAEJDBwBAQsKARsL' +
    'CgEBDCIBAAMVAyIBARgUARwNFAEBBwkJAQsYCQkBASMZEwoEATgJAgECHAEJDBwBAQsKARsLCgEBDCIBAAMVAyIBARgUARwN' +
    'FAEBBwkJAQsYCQkBASMZEwECCgQBNwkCHAIJCxwCAQsKARsLCgEBDCIBAAMVAyIBARgUARwNFAEBBwkJAQsYCQkBASMZEwEE' +
    'CgQBNgkBHAIJCxwBCQEBJCIBAAMVAyIBARgUARwNFAEBBwkJAQsYCQkBGAEXEBgBFxAYARkTAQcKAwEyCQQcAQkLHAEBJSIB' +
    'AAMVAyIBARgUARwNFAEBBwkJAQsYCQkBGAEVEBgBFRAYARkTAQkKAwEuCQMBAxwCCQocAQElIgEAAxUDIgEBGBQBHA0UAQEH' +
    'CQkBCxgJCQEYARUCGAMVCxgBFRAYARkTAQsKAwEqCgMBBhwBCQocAQElIgEAAxUDIgEBGBQBHA0UAQEHCQkBCxgJCQEYARUC' +
    'GAMVCxgBFRAYARkTAQ0KAwEmCgMBCBwCCQgcAgElIgEAAxUDIgEBGBQBHA0UAQgHCQkICxgJCQEYAQEQGAEBEBgBGRMBCxAG' +
    'ExEBARMDIwITAwoEDAcKAQELHAIJBxwBCQEBJSIBAAMBAyIBARUGAQwCFA8GAQEGCQkBDwkCAScZEwEJEAgTARgPEwEBARMB' +
    'GAIjARgDEwEKBAwIAQsJARwBCQccAQkBASUiAQADFQMiAQESCgEMAwECBwEMAQEcBwIBDwkBAUAQBBcIGAETDRgBEwEBARMB' +
    'GAETASMBEwIYARMBAQQMCAEMHAIJBhwBASYiAQADFQMiAQEOCgUBBQcBCwEMAQEcBwEBEAkBAT0QAxcEIwcYARMNGAEjAQEB' +
    'EwEYARMBIwETAhgBEwEBBAwJAQwcAQkGHAEBJiIBAAMVAyIBAQoJAgoDAQkHAgwBARwHAgEPCQIBOxACFwMjGgEBEwEYARMB' +
    'IwETAhgBEwEBBAwJAQwcAgkFHAEBJiIBAAMVAyIBAQYJBQEOBwEMAQEdCQEBEAkCATgQAxcCIwsXARgBEw0YARMBAQETARgB' +
    'EwEjARMCGAETAQEHDAcBDBwCCQMcAgEmIgEAAxUDIgEBAwcDCQEBEgcBDAEBHQkCARAJAgE1EAMXAyMMFwEYDxMBAQETARgB' +
    'EwEjARMCGAETAQEHDAcBDAkBHAEJAxwBCQEBJiIBAAMVAyIBBwQBFQcBDAEBHgkBAREJAQEzEAMXAyMOFwETEAEBEwEYARMB' +
    'IwETAhgBEwEBCAwHAQwcAgkCHAEBCQoSAQwiAQADFQMiAQEZBwEMAQEfCQEBEAkCATEQAhcDIxAXARMQAQETARgBEwEjARMC' +
    'GAETAQEIDAcBDRwBCQIcAQEJCgIYDgoCAQwiAQADFQMiAQEZBwEMAQEfCQIBEAkCAS4QAxcCIxIXARMQAQETARgBEwEjARMC' +
    'GAETAQEJDAcBDBwCCQEcAQEJCgIYDgoCAQwiAQADFQMiAQEZBwELAQEgCgEBEQoCASsQAxcDIxMXARMQAQETARgBEwEjARMC' +
    'GAETAQEKDAYBDRwDAQkKAhgOCgIBDCIBAAMVAyIBARoLAQEgCgIBEQoCASYQBRcDIyYBARMBGAETASMBEwIYARMBAQoMBwEM' +
    'CQEcAQkBAQkKAhgOCgIBDCIBAAMVAyIBARoLAgEgCgEBEgoBASIQBhcEIygBARMBGAETASMBEwIYARMBAQsMBgEMCAQBCAoC' +
    'GA4KAgEMIgEAAxUDIgEBGRAKDAYLAQEFDAMLAQwCCwEMBAECCgIBEQoCAR4QBhcEIxoXARMQAQETARgBEwEjARMCGAETAQEL' +
    'DAcBCwgBAQIIAgEHCgIYDgoCAQwiAQADFQMiAQEZEAoMBgsBAQUMCwEDIwIBAQoRIwEBCwkBFwcBChABFyQTEAEBEwEYARMB' +
    'IwETAhgBEwEBDAwGAQsIAQEDCAIBBgoCGA4KAgEMIgEAAxUDIgEBGRAKDAcBBQwLEwEWAiMCFgITAQoMFwMjARcDCgIBBgkB' +
    'FwETBRcBAQsQIxMRAQETARgCIwIYAhMBAQwMBwEJCAIBBAgCAQUKAhgOCgIBDCIBAAMVAyIBARkQCgwGCwEBBQsBDAoTARYB' +
    'EwEjARMCFgETAQEMFwETAiMBEwIXAQEBCgYBAQkBFwETBRcBAQ0TARgDIwEYAhMBAQQTAyMBEwQBAxMBGAIjAhgCEwEBBBMD' +
    'IwETAwEEEwMjAhMDARIMBwEICAEBBwkCAQMKAhgOCgIBDCIBAAMVAyIBARkQCgEXEwEWARMBIwETAhYBEwEBDBcBEwIjARMC' +
    'FwEBBgoCIwkBDBMBGAETAiMBEwEYARMBAQQTAyMBEwQBAxMBGAETASMCEwEYARMBAQQTAyMBEwMBBBMDIwETBAESDAcBCAgB' +
    'AQgJAgECCgIYDgoCAQwiAQADFQMiAQEZEAoBFxMBFgETASMBEwIWARMBAQwXARMCIwETAhcBAQkXAyMBFwMBDRMBGAETAiMB' +
    'EwEYARMBAQQTAyMBEwQBAxMBGAETASMCEwEYARMBAQQTAyMBEwMBBBMDIwETBAETDAcBBggCAQkJAgEBCgIYDgoCAQwiAQAD' +
    'FQMiAQEEDAUBEBAKARcTARYBEwEjARMCFgETAQEMFwETAiMBEwIXAQEJFwETAiMBEwIXAQENEwEYARMCIwETARgBEwEBBBMD' +
    'IwETBAEDEwEYARMBIwITARgBEwEBBBMDIwETAwEEEwMjARMEARMMBwEGCAEBCwkCCgIYDgoCAQwiAQADFQMiAQEEDAUBEBAK' +
    'ARcTARYBEwEjARMCFgETAQEMFwETAiMBEwIXAQEJFwETAiMBEwIXAQENEwEYARMCIwETARgBEwEBBBMDIwETBAEDEwEYARMB' +
    'IwITARgBEwEBBBMDIwETAwEEEwMjARMEARQMBwEFCQEBDAkBCgIYDgoCAQYGAwEDIgEAAxUDIgEBBAwFARAQCgEXEwEWARMB' +
    'IwETAhYBEwEBDBcBEwIjARMCFwEBCRcBEwIjARMCFwEBDRMBGAETAiMBEwEYARMBAQQTAyMBEwQBAxMBGAETASMCEwEYARMB' +
    'AQQTAyMBEwMBBBMDIwETBAEUDAcBBAUBCQEBDQoSCAEBBRkDAQMiBBUDIgEBBAwFARAQCgEXEwEWARMBIwETAhYBEwEBDBcB' +
    'EwIjARMCFwEBCRcBEwIjARMCFwEBDRMBGAETAiMBEwEYARMBAQQTAyMBEwQBAxMBGAETASMCEwEYARMBAQQTAyMBEwMBBBMD' +
    'IwETBAEVDAcBAwkBAQ4FAQkBARAIBgEHIgIAARUDIgEBBAwFARAQCgEXEwEWARMBIwETAhYBEwEBDBcBEwIjARMCFwEBCRcB' +
    'EwIjARMCFwEBDRMBGAETAiMBEwEYARMBAQQTAyMBEwQBAxMBGAETASMCEwEYARMBAQQTAyMBEwMBBBMDIwETBAEVDAcBAwkB' +
    'AQ8JAQEVCQghAgABFQMiAQEEDAUBDw0BEAoBFxMBFgETASMBEwIWARMBAQwXARMCIwETAhcBAQkXARMCIwETAhcBAQ0TARgB' +
    'EwIjARMBGAETAQEEEwMjARMEAQMTARgBEwEjAhMBGAETAQEEEwMjARMDAQQTAyMBEwQBCQwUAQIJAQEPCQEBHAkBIQIAARUD' +
    'IgEBBAwFAQ8NAQ8HDgINAQEXEwEWARMBIwETAhYBEwEBDBcBEwIjARMCFwEBCRcBEwIjARMCFwEBDRMBGAETAiMBEwEYARMB' +
    'AQQTAyMBEwQBAxMBGAETASMCEwEYARMBAQQTAyMBEwMBBBMDIwETBAEJDBQBAQkCAQ8JAQEgFQMiAQEEDAUBBAoEAQcNAQ8B' +
    'EAcPAQ0BARcTARYBEwEjARMCFgETAQEMFwETAiMBEwIXAQEJFwETAiMBEwIXAQEGPgMBBBMBGAETAiMBEwEYARMBAQQTAyMB' +
    'EwQBAxMBGAETASMCEwEYARMBAQQTAyMBEwMBBBMDIwETBAEDPgMBAwwVCQEBEAkBASAVAyIBAQ0KBAEHDQEPARAHDwENAQEX' +
    'EwEWARMBIwETAhYBEwEBDBcBEwIjARMCFwEBCRcBEwIjARMCFwEBBj4DAQQTARgBEwIjARMBGAETAQEEEwMjARMEAQMTARgB' +
    'EwEjAhMBGAETAQEEEwMjARMDAQQTAyMBEwQBAz4DAQMMFQkBARAJAQEgFQMiAQENCgQBBw8CEQESAhACEQIPAQ0BARcTARYB' +
    'EwEjARMCFgETAQEMFwETAiMBEwIXAQEJFwETAiMBEwIXAQEGPgMBBBMBGAETAiMBEwEYARMBAQQTAyMBEwQBAxMBGAETASMC' +
    'EwEYARMBAQQTAyMBEwMBBBMDIwETBAEDPgMBAwwVCQEBEAkBASAVAyIBAQ0KBAEHDwIRARIEEQIPAQ0BARcTARYBEwEjARMC' +
    'FgETAQEMFwETAiMBEwIXAQEJFwETAiMBEwIXAQENEwEYARMCIwETARgBEwEBBBMDIwETBAEDEwEYARMBIwITARgBEwEBBBMD' +
    'IwETAwEEEwMjARMEAQoMExMBAREJAQEgFQMiAQENCgQBBw4BDwERARIEEQIPAQ0BARcTARYCIwIWAhMBAQwXAyMBFwMBCRcB' +
    'EwIjARMCFwEBDRMBGAETAiMBEwEYARMBAQQTAyMBEwQBAxMBGAETASMCEwEYARMBAQQTAyMBEwMBBBMDIwETBAEdEwIBEAkB' +
    'AR0hAgABFQMiAQENCgQBBw4CEAERARICEQMPAQ0BARkKAgESCgIBDBcBEwIjARMCFwEBDRMBGAMjARgCEwEBBBMDIwETBAED' +
    'EwEYAiMCGAITAQEEEwMjARMDAQQTAyMCEwMBHRMCARAJAQEWCQchAgABFQMiAQENCgQBBw4CEAIRBQ8BDQEBGAoCARIKAgEN' +
    'FwMjARcDAWETAgEPCQEBEQgECQIBBiECAAEVAyIBAQ0KBAEHDgIQAxEDDwINAQEXCgIBEgoCAQ4TAyMBEwMBYRMCAQ8LEAgD' +
    'AQQZAwEDIgQVAyIBAQ0KBAEHDgIPAhACDwQNAQEXCgIBEQoCAXgTAgkJCAULAgoNCwIBBgYDAQMiAQADFQMiAQENCgQBBw0L' +
    'ARYKAgERCgIBeRMCAQ4LAgoNCwIBDCIBAAMVAyIBAQ0KBAEHDgIPAhABEQEQAQ8DDQEBFQoCAREKAgFkDAgBBgwJEwEMDAED' +
    'CwIKDAsCAQwiAQADFQMiAQENCgQBBw4CDwIRBQ8BDQEBFAoCAREKAgEVIwEBEyMCAQojAQEKIwIBCiMBAQojAgEMDAgBBgwW' +
    'AQMLAgoMCwIBDCIBAAMVAyIBAQ0KBAEHDgIPARABEgMRAg8BDQEBEwoCAREKAgETFgMjARYCEwEBDRMBFgIjAhYCEwEBBBMB' +
    'GAIjARgDAQQTARcCIwIXAhMBAQQXAyMBFwMBBBMBGAIjAhgCEwEBCQwIAQYMFgEECwEKDAsCAQwiAQADFQMiAQENCgQBBw0B' +
    'DwEQARIEEQIPAQ0BARIKAgERCgIBFBYBEwIjARMBFgETAQENEwEWARMCIwETARYBEwEBBBMBGAETASMBEwIYAQEEEwEXARMB' +
    'IwITARcBEwEBBBcBEwIjARMCFwEBBBMBGAETASMBEwIYARMBAQkMCAEGDBYBBAsCCgsLAgEMIgEAAxUDIgEBDQoEAQcPAhAB' +
    'EgQRAg8BDQEBESMCAREjAQoBAQojAgEJFgETAiMBEwEWARMBAQ0TARYBEwIjARMBFgETAQEEEwEYARMBIwETAhgBAQQTARcB' +
    'EwEjAhMBFwETAQEEFwETAiMBEwIXAQEEEwEYARMBIwETAhgBEwEBCQwIAQYMFgEECwIKCwsCAQwiAQADFQMiAQENCgQBBw8C' +
    'EAESBBECDwENAQEOEwEYAiMCGAITAQELEwEYAiMBGAMBBRMBFwIjAhcCEwEBBhYBEwIjARMBFgETAQENEwEWARMCIwETARYB' +
    'EwEBBBMBGAETASMBEwIYAQEEEwEXARMBIwITARcBEwEBBBcBEwIjARMCFwEBBBMBGAETASMBEwIYARMBAQkMCAEGDBYBBQsC' +
    'CgoLAgEMIgEAAxUDIgEBDQoEAQcNAQ8BEAcPAQ0BAQ4TARgBEwEjAhMBGAETAQELEwEYARMBIwETAhgBAQUTARcBEwEjAhMB' +
    'FwETAQEGFgETAiMBEwEWARMBAQ0TARYBEwIjARMBFgETAQEEEwEYARMBIwETAhgBAQQTARcBEwEjAhMBFwETAQEEFwETAiMB' +
    'EwIXAQEEEwEYARMBIwETAhgBEwEBCQwIAQYMFgEFCwIKCgsCAQwiAQADFQMiAQENCgQBBw0BDwEQBw8BDQEBDhMBGAETASMC' +
    'EwEYARMBAQsTARgBEwEjARMCGAEBBRMBFwETASMCEwEXARMBAQYWARMCIwETARYBEwEBDRMBFgETAiMBEwEWARMBAQQTARgB' +
    'EwEjARMCGAEBBBMBFwETASMCEwEXARMBAQQXARMCIwETAhcBAQQTARgBEwEjARMCGAETAQEJDAgBBgwWAQYLAQoKCwIBDCIB' +
    'AAMVAyIBAQ0KBAEHDQEPARADDwQOAQ0BAQ4TARgBEwEjAhMBGAETAQELEwEYARMBIwETAhgBAQUTARcBEwEjAhMBFwETAQEG' +
    'FgETAiMBEwEWARMBAQ0TARYBEwIjARMBFgETAQEEEwEYARMBIwETAhgBAQQTARcBEwEjAhMBFwETAQEEFwETAiMBEwIXAQEE' +
    'EwEYARMBIwETAhgBEwEBCQwIAQYMFgEGCwIKCQsCAQwiAQADFQMiAQENCgQBBw0LAQ4TARgBEwEjAhMBGAETAQELEwEYARMB' +
    'IwETAhgBAQUTARcBEwEjAhMBFwETAQEGFgETAiMBEwEWARMBAQ0TARYBEwIjARMBFgETAQEEEwEYARMBIwETAhgBAQQTARcB' +
    'EwEjAhMBFwETAQEEFwETAiMBEwIXAQEEEwEYARMBIwETAhgBEwEBCQwIAQYMFgEHCwEKCQsCAQwiAQADFQMiAQENCgQBCA0B' +
    'DggNAQEOEwEYARMBIwITARgBEwEBCxMBGAETASMBEwIYAQEFEwEXARMBIwITARcBEwEBBhYBEwIjARMBFgETAQENEwEWARMC' +
    'IwETARYBEwEBBBMBGAETASMBEwIYAQEEEwEXARMBIwITARcBEwEBBBcBEwIjARMCFwEBBBMBGAETASMBEwIYARMBAQkMCAEG' +
    'DBYBBwsCCggLAgEMIgEAAxUDIgEBDQoEAQgNARAFDgMNAQEOEwEYARMBIwITARgBEwEBCxMBGAETASMBEwIYAQEFEwEXARMB' +
    'IwITARcBEwEBBhYBEwIjARMBFgETAQENEwEWARMCIwETARYBEwEBBBMBGAETASMBEwIYAQEEEwEXARMBIwITARcBEwEBBBcB' +
    'EwIjARMCFwEBBBMBGAETASMBEwIYARMBAQkMCAEGDBYBBwsCCggLAgEMIgEAAxUDIgEBDQoEAQgNARAEDwEOAw0BAQ4TARgB' +
    'EwEjAhMBGAETAQELEwEYARMBIwETAhgBAQUTARcBEwEjAhMBFwETAQEGFgETAiMBEwEWARMBAQ0TARYBEwIjARMBFgETAQEE' +
    'EwEYARMBIwETAhgBAQQTARcBEwEjAhMBFwETAQEEFwETAiMBEwIXAQEEEwEYARMBIwETAhgBEwEBCQwIAQYMFgEICwEKCAsC' +
    'AQwiAQADFQMiAQEZDQEQAg8DDgMNAQEOEwEYARMBIwITARgBEwEBCxMBGAETASMBEwIYAQEFEwEXARMBIwITARcBEwEBBhYB' +
    'EwIjARMBFgETAQENEwEWARMCIwETARYBEwEBBBMBGAETASMBEwIYAQEEEwEXARMBIwITARcBEwEBBBcBEwIjARMCFwEBBBMB' +
    'GAETASMBEwIYARMBAQkMCAEGDBYBCAsCCgcLAgEMIgEAAxUDIgEBGQ0BDgEPBA4DDQEBDhMBGAETASMCEwEYARMBAQsTARgB' +
    'EwEjARMCGAEBBRMBFwETASMCEwEXARMBAQYWARMCIwETARYBEwEBDRMBFgETAiMBEwEWARMBAQQTARgBEwEjARMCGAEBBBMB' +
    'FwETASMCEwEXARMBAQQXARMCIwETAhcBAQQTARgBEwEjARMCGAETAQEJDAgBBgwWAQkLAQoHCwIBDCIBAAMVAyIBARkNAQ4B' +
    'DwQOAw0BAQ4TARgBEwEjAhMBGAETAQELEwEYARMBIwETAhgBAQUTARcBEwEjAhMBFwETAQEGFgETAiMBEwEWARMBAQ0TARYB' +
    'EwIjARMBFgETAQEEEwEYARMBIwETAhgBAQQTARcBEwEjAhMBFwETAQEEFwETAiMBEwIXAQEEEwEYARMBIwETAhgBEwEBCQwI' +
    'AQYMFgEJCwIKBgsCAQwiAQADFQMiAQEZDQIPBA4DDQEBDhMBGAETASMCEwEYARMBAQsTARgBEwEjARMCGAEBBRMBFwETASMC' +
    'EwEXARMBAQYWARMCIwETARYBEwEBDRMBFgETAiMBEwEWARMBAQQTARgCIwEYAwEEEwEXAiMCFwITAQEEFwMjARcDAQQTARgC' +
    'IwEYAxMBAQkMCAEGDBYBCQsCCgYLAgEMIgEAAxUDIgEBGQ0CDgEPAw4DDQELAwwECwcTARgBEwEjAhMBGAETAQELEwEYARMB' +
    'IwETAhgBAQUTARcBEwEjAhMBFwETAQEFIwkBDCMIAQQjCAEDIwgBAyMJAQMjCAEJDAgBBgwWAQoLAgoFCwIBDCIBAAMVAyIB' +
    'ARkNAw4BDwIOAw0BDA4TARgBEwEjAhMBGAETAQELEwEYARMBIwETAhgBAQUTARcBEwEjAhMBFwETAQEBCgUWARMFFgEKAwEH' +
    'CwMTARYBEwUWAQEEGAETBRgBEwEBAxMBFwETBRcBAQMJARcBEwUXAQEEGAETBRgBEwEKAQEIDAgBBgwWAQoLAgoFCwIBDCIB' +
    'AAMVAyIBARkNBA4BDwIOAg0BDA4TARgBEwEjAhMBGAETAQELEwEYARMBIwETAhgBAQUTARcBEwEjAhMBFwETAQoCAQQWARMF' +
    'FgEBAgoDPgMLBAEBEwEWARMFFgEBBBgBEwUYARMBAQMTARcBEwUXAQEDCQEXARMFFwEBBBgBEwUYARMBAQEKAj4DAQMMCAEG' +
    'DBYBCwsBCgULAgEMIgEAAxUDIgEBGQ0FDgQNAQwKCwEMAxMBGAIjAhgCEwEKCxMBGAIjARgDCgUTARcCIwIXAhMBAQYWBwEE' +
    'CgE+AwsCAQMTARYHAQQYBxMBAQMTARcHAQMJARcHAQQYBxMBAQIKAT4DCwMMCAoGDBYBCwsCCgQLAgEMIgEAAxUDIgEBGQ0I' +
    'DgENAQoDDAQKCAEDCgEBAgUBASUTBwEFPgMBBRMIAQQTCAEDEwgBBBMHAQQTCAEDPgMKAQYCDAgKBgwWCgEBCgsCEwQLAgEM' +
    'IgEAAxUDIgEBIgoDARAKAgEBBQEBmgoBBgEKAQELCgETBAEOIgEAAxUDIgEBJAoCARAKAQEBBQIBmQoBBgEKAgEKCgETBAEO' +
    'IgEAAxUDIgEBJQoCAQ8KAgEBBQEBmQoBBgIKAgEJCgETBAEOIgEAAxUDIgEBJgoDAQ4KAQEBBQEBmQoBBgMKAQEJCgEBEiIB' +
    'AAYiARYDASUKAgENCgEBAQUCAT8FAgEIBQMBBwUCAQkFAwE3CgEBAQYCCgIBCAoBARIiAQAGIgEWAwEmCgIFAQEMCgEBAQUB' +
    'AT4FBAEHBQMBBwUEAQcFAwE3CgIGAQEBBgEKAQkBAQcKAQESIgEABiIBFgMBKAoCAQsKAgUBAT4FBAEHBQMBBwUDAQgFAwE4' +
    'CgEGAQECBgEJAQEGBgEKAQESIgEABiIBFgMBKQoCAQsKAQEBBQEBmAoBBgEBAgYBCQIBBQYBCgEBEiIBAAYiARYDASoKAwEJ' +
    'CgEBAQUBAZgKAQYBAQMGAQkCAQQGAQoBARIiAQAGIgEWAwEsCgIBCQoBBQEBmAoBBgEBBAYBCQEBBAYBCgEBEiIBAAYiAQEw' +
    'CgIBCAoBAQEFAQGXCwEGAQEEBgIJAQEDBgEKAgERIgEABiIQCgQBHgUBCgIBBwoBBQEBlwsBBgEBBQYBCQIBAgYBAQEKAQER' +
    'IgEAFSIBAQMKBgEbCgIBBgoBBQIBOwUDAQgFAwEHBQMBCAUDATgLAQYCAQUGAQcBAQIGAQEBCgEBESIBABUiAQEICgYBFwoC' +
    'AQUKAgUBATsFBAEHBQQBBgUDAQcFBAE4CwIGAQEFBgIHAQEBBgEBAQoBAREiAQAVIgEBDQoGARQKAgEECgEFAQE7BQMBCAUD' +
    'AQcFAwEIBQMBOQsBBgEBBgYBBwIGAQEBCgEBESIBABUiAQESCgYBEAoCAQMKAgUBAZYLAQYBAQcGAQcCAQEKAQERIgEAFSIB' +
    'ARcKBgEMCgMBAgoBBQEBdQcBARAHAQEOBwELAQYBAQcGAgcBAQEKAQERIgEAFSIBARwKBgEJCgIBAQoCAXMMBgEKDAYBCgwG' +
    'AQcGAQwGAQ4iAQAVIgEBIQoGAQUKAgEBCgEFAQFyDAYBCgwGAQoMBgEIDAYBDiIBABUiAQEmCgYBAQUBCgMBcgwGAQoMBgEK' +
    'DAYBCAwGAQ4iAQAVIgEZAQEHGAEBCRkBAQgZAQEIGAEBBgoDGQIQGAEFFCQBBwwIAQIMCAEZDAYBCgwGAQoMBgEIDAYBDiIB' +
    'ABUiARkBAQcYAQYBAQgZAQEIGQEBCBgBAQkZAhAYAQUUJAEEEBcBFwwGAQoMBgEKDAYBCAwGAQ4iAQAVIgEZAQEHGAEGAQEI' +
    'GQEBCBkBAQgYAQEJGQIQGAEFFCQBBBAXARcMBA4CAQoMBQ4BAQoMBA4CAQgMBA4CAQ4iAQAVIgEZAQEHGAEBCRkBAQgZAQEI' +
    'GAEBCRkCEBgBBRQkAQQQFwEXDAQRAQ8BAQoMBBECAQoMAxECDwEBCAwEEQEPAQEOIgEAFSIBATAQGAEFFCQBBBAXARcMBBEB' +
    'DwEBCgwEEQIPAQEJDAMRAg8BAQgMBBEBDwEBDiIBABUiAQEwEBgBBRQkAQQQFwEXDwEMAxEBDwEBCg8BDAMRAgEJDwIMAhEC' +
    'DwEBCA8BDAMRAQ8BAQ4iAQAVIgEBMBAYAQUUJAEEEBcBFw8BDAUBCg8BDAUBCQ8CDAUBCA8BDAUBDiIBABUiAQEwEBgBBRQk' +
    'AQQQFwEWEAQMAwEKEAMMAwEJEAQMAwEIEAMMAwEOIgEAFSIBAU0UJAEEEBcBFwwGAQoMBgEKDAYBCAwGAQ4iAQAVIgEBTRQk' +
    'AQQQFwEXDAYBCgwGAQoMBgEIDAYBDiIBABUiAQFNFCQBBBAXARcMBgEKDAYBCgwGAQgMBgEOIgEAFSIBAU0UJAEEEBcBFwwG' +
    'AQoMBgEKDAYBCAwGAQ4iAQAVIgEBMBAYAQUUJAEEEBcBFwwGAQoMBgEKDAYBCAwGAQ4iAQAVIgEBMBAYAS0QFwE6CQEFAQEK' +
    'CQIBESIBABUiAQEwEBgBLRAXAToJAQUBAQsJAQERIgEAFSIBATAQGAEtEBcBOQkCAQwJAQUBARAiAQAVIgEBMBAYARMiOwEv' +
    'CQEFAQEMCQIBECIBABUiAQEwEBgBEiI+AS0JAQEOCQEBECIBABUiAQEwEBgBECICAD0iAgErCQIBDgkCAQ8iAQAVIgEBMBAY' +
    'AQ8iAgA+IgMBKgkBBQEBDgkCAQ8iAQAVIgEBVSIDAEEiAgEpCwEBEAkBAQ8iAQAVIgEBVCIDAEIiBAEmCwIBEAkCAQ4iAQAV' +
    'IgEBUyICAEciAgElCwEBEQkCAQ4iAQAVIhQBJCMCIhwASCIeAQcFAQsBARIJAQEIIgcAFQETIgMBISMCAIIiAgEGCwIBEgkC' +
    'AQUiAwAaARYjAgEeIwMAhCIBIwIBBAsBARQJAQEEIgMAGgEYIwMBGiMDAIgjAwEBCwIBFAkBAQIiAwAbIhcBBCMDARcjBACI' +
    'IwQLAQEVCQEiAwAzIgMBBCMCIgEBEyMDAI4jAwETIgMANyICAQUiAQEBGgUBBhoHIgEAkiIBGgcBBhoGIgEAOiIDAQMiARgB' +
    'GgUBBhoHIgEAkiIBGgcBBhoGIgEAPCIFABMiAQCSIgEAEyIBABI=',
  },
} as const;
